### PR TITLE
Turn closure bodies from exprs into blocks if there are comments

### LINKED ISSUE #4384: formatting fails if closure is split into multiple lines by comment
**Input**

```rust
fn main() {
    let v: Vec<i32> = vec![1, 2, 3, 4];

    v.iter()
        .filter(|    x| 
    // bla bla
             **x != 2)
        .for_each(|x| println!("{}", x));
}
```

**Output**

```rust
fn main() {
    let v: Vec<i32> = vec![1, 2, 3, 4];

    v.iter()
        .filter(|    x| 
    // bla bla
             **x != 2)
        .for_each(|x| println!("{}", x));
}
```

**Expected output**

Something more similar to
```rust
fn main() {
    let v: Vec<i32> = vec![1, 2, 3, 4];

    v.iter()
        .filter(|x| 
        // bla bla
         **x != 2)
        .for_each(|x| println!("{}", x));
}
```

**Meta**

- rustfmt version: `rustfmt 1.4.20-nightly (48f6c32 2020-08-09)`

- From where did you install rustfmt?: rustup component

### PR DESCRIPTION
**Pull request by Solumin**
A closure like this:
```
let x = ||
    // a comment
    some_body_expr;
```
should be a block instead of a single expression, as per the [fmt-rfcs](https://github.com/rust-dev-tools/fmt-rfcs/blob/master/guide/expressions.md#closures).

Closes #4384

### CODE REVIEW

**Comment by Solumin** [comment]
My apologies for forgetting to squash commits before uploading to master, it's been a while.

**Comment by Solumin** [comment]
I thought of a really annoying edge case:
```rust
let one_liner = || /* ? */ 1;
```
This PR will rewrite it as:
```rust
let one_liner = || { /* ? */
    1
};
```
I'm pretty sure this is because `rewrite_closure_with_block` (which calls `rewrite_block_with_visitor`) turns it into:
```rust
let one_liner = ||
    1
};
```
and `combine_strs_with_missing_comments` will try to put all the strings on the same line due to there being no newlines in the original source: https://github.com/rust-lang/rustfmt/blob/f7ba2dbcf2ce9dd086c06b6b7e89b399fdd25374/src/formatting/comment.rs#L204-L212

An edge case, to be sure, but this whole PR is addressing edge cases, so I'll see what I can figure out.

File: src/formatting/closures.rs [hunk 1]
```diff
@@ -65,6 +66,33 @@ pub(crate) fn rewrite_closure(
...
+        // wrapped in a block. Since there's no return type annotation on closures with expr
+        // bodies, look for comments after the second "|".
+        let between_span = mk_sp(
+            context.snippet_provider.span_after(span, "|"),
+            body.span.lo(),
+        );
+        let between_span = mk_sp(
+            context.snippet_provider.span_after(between_span, "|"),
+            body.span.lo(),
+        );
```
Comment (calebcartwright) [inline src/formatting/closures.rs:79]: Instead of the multiple steps to build out this span ourselves, could we use the span associated with the param block from the closure expression? We're not currently using it but I believe it would make it easier to derive the "between span"

https://github.com/rust-lang/rustfmt/blob/f7ba2dbcf2ce9dd086c06b6b7e89b399fdd25374/src/formatting/expr.rs#L192-L196

File: tests/target/issue-4384.rs [hunk 2]
```diff
@@ -0,0 +1,28 @@
...
+        1
+    };
+
+    let nested_closure = || {
+        // indent + wrap in a block.
+        || 1
+    };
+
+    let nested_comment_closure = || {
+        // if you see this code in real life, run.
```
Comment (calebcartwright) [inline tests/target/issue-4384.rs:21]: :rofl:

File: src/formatting/closures.rs (hunk 1 above)
Comment (Solumin) [reply src/formatting/closures.rs:79]: That turns `between_span` into:
```rust
let between_span = mk_sp(param_span.hi(), body.span.lo());
```
which is significantly cleaner, at the cost (?) of passing in one more argument. That looks much better to me!

**Comment by Solumin** [comment]
@ayazhafiz Personally I'd consider that a separate issue, but I _think_ the fix is quite similar to what I've added in this PR. So I'm going to pass on fixing that for now.

**Comment by Solumin** [comment]
I have encountered something quite fun.

I added this test case:
```rust
let one_line = || /* one line */ 1;
```
with expected output:
```rust
let one_line = || { /* one line */
    1
};
```
Because, as I mentioned above, `combine_strs_with_missing_comments` tries to put the comment on the same line as it is in the original source.

But this fails because rustfmt thinks that the output should be:
```rust
let one_line = || {
    /* one line */
    1
};
```
That's great, that's what I'd prefer to see anyway! So let's change the test case to use that output--
```rust
Mismatch at tests/source\issue-4384-2.rs:1:
 fn main() {
-    let one_line = || {
-        /* one line */
+    let one_line = || { /* one line */
         1
     };
 }
```

Um. rustfmt is somehow generating both versions?

**Comment by calebcartwright** [comment]
> But this fails because rustfmt thinks that the output should be:
> 
> ```rust
> let one_line = || {
>     /* one line */
>     1
> };
> ```



> So let's change the test case to use that output--
> 
> ```rust
> Mismatch at tests/source\issue-4384-2.rs:1:
>  fn main() {
> -    let one_line = || {
> -        /* one line */
> +    let one_line = || { /* one line */
>          1
>      };
>  }
> ```
> 
> Um. rustfmt is somehow generating both versions?

I'm not sure I follow what you're saying here, and I'm unable to reproduce this locally with the latest changes on your branch. 

The preservation of original line placement with `combine_strs_with_missing_comments` is intentional, so that may not be a great approach in this case. As @ayazhafiz alluded to on the other thread, utilizing different comment util function like `rewrite_missing_comment` or `recover_missing_comment_in_span` may be a better fit for option 2. 

I also wouldn't be too concerned about a minor refactor to add a new param to `rewrite_closure_with_block` to accept the target span as mentioned in your option 1. It's a private/internal function that's only called from a handful of places, and the param could even be Option wrapped with `rewrite_closure_with_block` using the body span in the none case.

**Comment by Solumin** [comment]
Thanks @ayazhafiz and @calebcartwright, the finer-grained control from using `rewrite_missing_comment` gives a better result.

I'm happy with the state of this now, it covers every case I could think of.

**Comment by calebcartwright** [comment]
Thanks @Solumin! Could you rebase/address the conflicts? Will take a final look over afterwards

**Comment by Solumin** [comment]
I don't see any conflicts now. Or at least GitHub says it can be merged.

**Comment by calebcartwright** [comment]
I can squash the commits but there's conflicts preventing a rebase. No worries, will look at it later

**Comment by Solumin** [comment]
I got it, just had to look up the right git incantation. Sorry!

File: src/formatting/closures.rs [hunk 3]
```diff
@@ -65,6 +67,35 @@ pub(crate) fn rewrite_closure(
...
+            .attrs
+            .first()
+            .map(|attr| attr.span)
+            .unwrap_or(body.span);
+        let between_span = Span::between(arg_span, first_span);
+        if contains_comment(context.snippet(between_span)) {
+            return rewrite_closure_with_block(body, &prefix, context, body_shape).and_then(|rw| {
+                let mut parts = rw.splitn(2, "\n");
+                let head = parts.next().unwrap();
+                let rest = parts.next().unwrap();
```
[the remark this answers is not in the document]
Comment (Solumin) [reply src/formatting/closures.rs]: Done.

File: src/formatting/closures.rs [hunk 4]
```diff
@@ -65,6 +67,35 @@ pub(crate) fn rewrite_closure(
...
+                let block_shape = shape.block_indent(context.config.tab_spaces());
+                let indent = block_shape.indent.to_string_with_newline(context.config);
+                let missing_comment =
+                    rewrite_missing_comment(between_span, block_shape, context).unwrap();
```
[the remark this answers is not in the document]
Comment (Solumin) [reply src/formatting/closures.rs]: Done.

**Comment by calebcartwright** [comment]
Perfect, thank you!
