### PR TITLE
fix: correct generic bound indentation [2.x/master]

### LINKED ISSUE #4636: Indentation issue on first item in generic bounds
Reported in https://github.com/rust-lang/rust/pull/80843#discussion_r554476529

**Input**

```rust
pub trait PrettyPrinter<'tcx>:
    Printer<
        'tcx,
        Error = fmt::Error,
        Path = Self,
        Region = Self,
        Type = Self,
        DynExistential = Self,
        Const = Self,
    > + fmt::Write
    {
         //
    }
```

**Output**

```rust
pub trait PrettyPrinter<'tcx>:
    Printer<
    'tcx,
    Error = fmt::Error,
    Path = Self,
    Region = Self,
    Type = Self,
    DynExistential = Self,
    Const = Self,
> + fmt::Write
{
    //
}
```

**Expected output**

```rust
pub trait PrettyPrinter<'tcx>:
    Printer<
        'tcx,
        Error = fmt::Error,
        Path = Self,
        Region = Self,
        Type = Self,
        DynExistential = Self,
        Const = Self,
    > + fmt::Write
{
    //
}
```

**Meta**

Bisected to 1.4.28 where a bug fix for handling comments between bounds was introduced (#4474)

### PR DESCRIPTION
**Pull request by calebcartwright**
Fixes #4636

### CODE REVIEW

File: src/formatting/types.rs [hunk 1]
```diff
@@ -933,7 +933,7 @@ fn join_bounds_inner(
                 _ => false,
             };
 
-            let shape = if i > 0 && need_indent && force_newline {
+            let shape = if need_indent && force_newline {
```
Comment (calebcartwright) [inline src/formatting/types.rs:936]: The way the code is structured, `force_newline` will always be false on the first pass through and a second pass is only triggered in situations where we have to use multiple lines to format. As such this index check only serves to cause a bug

File: src/formatting/types.rs [hunk 2]
```diff
@@ -964,22 +964,21 @@ fn join_bounds_inner(
                 joiner
             };
 
-            let (trailing_str, extendable) = if i == 0 {
+            let (extendable, trailing_str) = if i == 0 {
                 let bound_str = item.rewrite(context, shape)?;
-                let bound_str_clone = bound_str.clone();
-                (bound_str, is_bound_extendable(&bound_str_clone, item))
+                (is_bound_extendable(&bound_str, item), bound_str)
```
Comment (calebcartwright) [inline src/formatting/types.rs:969]: Neither related to the underlying bug nor necessary to fix it, just noticed while in here that we were unnecessarily cloning the formatted bound
