### PR TITLE
don't convert implict ABI when doing so could fail to preserve semantics

### LINKED ISSUE #2908: extern is replaced with extern "C" for wasm extern functions
I am getting this diff with rustfmt in stdsimd, is this intended (@nrc , @topecongiro ) / correct (cc @alexcrichton) ?

```diff
 #[wasm_bindgen(module = "child_process", version = "*")]
-extern {
+extern "C" {
     #[wasm_bindgen(js_name = execSync)]
     fn exec_sync(cmd: &str) -> Buffer;
 }
```

### PR DESCRIPTION
**Pull request by calebcartwright**
Fixes #2908 (option 3 from https://github.com/rust-lang/rustfmt/issues/2908#issuecomment-650588865)

Happy to open a separate/alternative PR with option 2 if we'd rather go that route :+1:

### CODE REVIEW

File: src/formatting/utils.rs [hunk 1]
```diff
@@ -147,19 +147,28 @@ pub(crate) fn format_extern(
...
+            Cow::from("extern ")
+        }
+        ast::Extern::Explicit(ast::StrLit {
+            symbol_unescaped, ..
+        }) if !explicit_abi && symbol_unescaped == rustc_span::sym::C => Cow::from("extern "),
+        ast::Extern::None => format_explicit_abi("Rust"),
+        ast::Extern::Implicit => format_explicit_abi("C"),
+        ast::Extern::Explicit(ast::StrLit {
+            symbol_unescaped, ..
+        }) => format_explicit_abi(&symbol_unescaped.to_string()),
```
Comment (calebcartwright) [inline src/formatting/utils.rs:171]: I elected to do a bit of refactoring here. This refactoring avoids homogenizing the ABIs and continues to leverage the extern variants, which also makes it easier to do symbol comparisons on the ABIs. Hopefully it's still sufficiently easy to read, as there is a bit of logic involved with formatting these correctly

File: tests/source/extern.rs [hunk 2]
```diff
@@ -63,3 +63,20 @@ libc::c_long;
...
+     fn foo() -> Bar;
+ }
+
+// Users that have an existing explicit ABI would need to convert to implicit
+// manually, as rustfmt will be conservative and not attempt to convert explicit
+// to implicit in the wasm case.
+#[wasm_bindgen]
+extern "C" {
+       fn foo() -> Bar;
+}
```
Comment (calebcartwright) [inline tests/source/extern.rs:82]: Unfortunately I believe that an explicit C ABI became common practice with wasm_bindgen at least in part because of rustfmt 1.x behavior. However, I don't think we should attempt to help those users convert _back_ to an implicit ABI as it seems to risky/error prone IMO; with this change, rustfmt 2.0 by default would permit users to do what they want and will no longer force Explicit ABIs.
