### PR TITLE
Fix broken tuple pattern

### LINKED ISSUE #3728: Incorrect formatting of tuple destructuring
rustfmt 1.4.3-nightly 2019-08-03-3adfb08

Incorrectly formats the following ([playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=1d936e8a9c678616bd735017339ff1f6)):

```rust
fn main() {
    let foo = |(c,)| c;
    foo((1,));
}
```

Into:

```rust
fn main() {
    let foo = |(c)| c;
    foo((1,));
}
```

This breaks the tuple destructuring since `(c) == c`.

A workaround until this is fixed is to do:

```rust
fn main() {
    let foo = |(c, ..)| c;
    foo((1,));
}
```

_I think_ this was introduced some time since 2019-07-29, since that was my last nightly which didn't exhibit this behavior for me.

### PR DESCRIPTION
**Pull request by topecongiro**
Closes #3728.

### CODE REVIEW

File: tests/target/issue-1021.rs [hunk 1]
```diff
@@ -15,7 +15,7 @@ fn main() {
         (true, ..) => (),
         (.., true) => (),
         (..) => (),
-        (_) => (),
+        (_,) => (),
```
Comment (topecongiro) [inline tests/target/issue-1021.rs]: The current test is actually incorrect: `(_,)` and `(_)` are different.

Comment (topecongiro) [reply tests/target/issue-1021.rs]: The change from `(_,)` to `(_)` in this file was introduced in a recent PR, so I believe rustfmt had been working correctly before that.
