### PR TITLE
Let empty files be empty files

### LINKED ISSUE #5364: rustfmt fails on an empty file; --check's diff doesn't result in properly formatted file
Generate an empty file, and run `rustfmt --check` on it:

```sh
$ touch zero_lines.rs
$ rustfmt --check zero_lines.rs
Diff in /Users/roy/code/random/test-crate/src/zero_lines.rs at line 1:
+
+
```

So, this is interesting; to me, an empty file is inherently correctly formatted (what else would you put in the file?). But the diff emitted by `rustfmt` here indicates that, instead of just an empty file, that it would like a file with two blank lines. But if you give it what it wants:

```sh
$ printf '\n\n' > two_lines.rs
$ rustfmt --check two_lines.rs
Diff in /Users/roy/code/random/test-crate/src/two_lines.rs at line 1:

-

$
```
… the file is still not valid, and … the diff is nonsensical. This diff indicates a 3 line file, where the second line is removed, which doesn't match our input.

What `rustfmt --check` seems to want, is:

```sh
$ printf '\n' > one_line.rs
$ rustfmt --check one_line.rs
$
```

A file with one line in it. Which is fairly arbitrary (why have a blank line?).

This is in a crate whose `lib.rs` is empty, as it's just a placeholder for `bin/a.rs`, `bin/b.rs`, etc. stuff.

In practice, I'm going to slap a docstring into this particular `lib.rs` to hack around this.

### PR DESCRIPTION
**Pull request by notpeter**
No longer add a "final newline" to empty files. 
Empty files shouldn't need need trailing newlines.

- Fixes: #5364

Since this is a breaking change, I've done my best to feature gate this behind `StyleEdition::Edition2027`. Please let me know if this should be handled differently.

New tests:
- `append_newline_adds_newlines_before_2027`
- `append_newline_leaves_empty_files_empty_in_2027`
- `newline_file` (existing 2024 behavior; excess newline is preserved)
- `reorder_modules_2027` (2027 behavior test extracted from `reorder_modules`)

The empty file `mod.rs` test fixtures for the `reorder_modules` test were previously being re-used for multiple editions (2015, 2024, 2027), but since 2027 now requires those files be actually empty instead of `\n`, I moved `{enabled,disabled_style_edition_2027.rs}` from `reorder_modules/` to a new `reorder_modules_2027/` and mirrored the `mod.rs` test fixture structure.

The existing `empty_file.rs` test (empty file becomes newline) remains untouched. (config not specified; so 2015).

Update1: Fixed reorder_modules
Update2: 2027 tests pass on nightly, fail on stable. Unsure of the proper fix.
Update3: Renamed `empty_file_style_edition_2024` to `newline_file` because it's not actually an empty file.
Update4: Implemented ytmimi's suggestion and fixed tests.

### CODE REVIEW

File: src/source_file.rs [hunk 1]
```diff
@@ -16,8 +16,12 @@ use crate::create_emitter;
...
 
 // Append a newline to the end of each file.
-pub(crate) fn append_newline(s: &mut String) {
-    s.push('\n');
+pub(crate) fn append_newline(s: &mut String, style_edition: StyleEdition) {
+    if style_edition <= StyleEdition::Edition2024
+        || style_edition >= StyleEdition::Edition2027 && !s.is_empty()
+    {
+        s.push('\n');
+    }
```
Comment (ytmimi) [inline src/source_file.rs]: Can't the logic just get simplified to:

```rust
if style_edition >= StyleEdition::Edition2027 && s.is_empty() {
   return
}

s.push('\n');
```

**Review by ytmimi — COMMENTED** [review]
Please investigate test failures. Also see my suggestion for simplifying the conditional logic.

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rustfmt/6839/bdab1017c6bf9291654fa5cd15163d011c8194b6..868d0166262ee795c95d4b20ff42534a2fb40485)*

File: tests/source/reorder_modules_2027/_abcd/mod.rs [hunk 2]
```diff
@@ -0,0 +1 @@
+
```
Comment (ytmimi) [inline tests/source/reorder_modules_2027/_abcd/mod.rs]: I want to make sure I understand. We're adding newlines to empty source files to show that the formatting in the corresponding target files removes the newline?

Comment (notpeter) [reply tests/source/reorder_modules_2027/_abcd/mod.rs]: Good catch.  I had just duplicated the existing test set and adjusted `target/reorder_modules_2027/*/mod.rs` but I should make the `source` files empty there too.

**Review by ytmimi — APPROVED** [review]

**Comment by ytmimi** [comment]
This PR was causing CI issues when trying to merge rust-lang/rust changes backing into rustfmt (https://github.com/rust-lang/rustfmt/pull/6939). I'm not sure why that's the case, but I reverted these changes in that PR so they're no longer on the `main` branch.
