### PR TITLE
Fix test config dir

### LINKED ISSUE #4592: Fail when recoverable parser errors occurs in ignored files with rustfmt-recursive
**Describe the bug**

Fail when formatting recoverable parser errors occurs in ignored files with rustfmt-recursive.
I found it working #4113 with `issue-3779/ice.rs` 

**To Reproduce**

1. Add `// rustfmt-recursive: true` to the head of `tests/source/issue-3779/lib.rs`
2. run `cargo make test`
3. Fail with following error

```
error: invalid suffix `x` for integer literal
 --> tests/source/issue-3779/ice.rs:2:5
  |
2 |     1x;
  |     ^^ invalid suffix `x`
  |
  = help: the suffix must be one of the integral types (`u32`, `isize`, etc)
```

**Expected behavior**

`cargo make test` passes

**Meta**

- rustfmt version: current master 81ad114d12c2d7dd2253afd64f0d2019697aa6de

### PR DESCRIPTION
**Pull request by sasurau4**
Fix #4592 
Part of #4113 

Test config with `tests/config/` make ignore dir root to `tests/` and it return false with files like `tests/source/foo/bar.rs`.
I remove `config/` and add test cases to ignore_path module.

### CODE REVIEW

File: src/formatting/syntux/session/ignore_path.rs [hunk 1]
```diff
@@ -60,4 +60,35 @@ mod test {
             _ => {}
         };
     }
+    #[test]
+    fn test_ignore_path_set_with_dir() {
+        match option_env!("CFG_RELEASE_CHANNEL") {
+            // this test requires nightly
+            None | Some("nightly") => {
```
Comment (calebcartwright) [inline src/formatting/syntux/session/ignore_path.rs:67]: I know the other test here is using this pattern, but we've moved towards leveraging the below pattern elsewhere in tests that are nightly-only

```rust
if !is_nightly_channel!() {
    return;
}
```

Would you mind updating this (and the one above) to follow this pattern? `is_nightly_channel` is available at the crate root. Using this helps keeps things a bit more encapsulated, and also helps reduce some of the indentation levels

**Review by calebcartwright — COMMENTED** [review]
LGTM, thanks for the fix! One minor refactor tweak requested, though we could address that in a follow up if you'd prefer

File: src/formatting/syntux/session/ignore_path.rs (hunk 1 above)
Comment (sasurau4) [reply src/formatting/syntux/session/ignore_path.rs]: I'll follow this pattern!

File: src/formatting/syntux/session/ignore_path.rs [hunk 2]
```diff
@@ -42,22 +42,48 @@ mod test {
...
-                let ignore_path_set = IgnorePathSet::from_ignore_list(&config.ignore()).unwrap();
-
-                assert!(ignore_path_set.is_match(&FileName::Real(PathBuf::from("src/foo.rs"))));
-                assert!(ignore_path_set.is_match(&FileName::Real(PathBuf::from("bar_dir/baz.rs"))));
-                assert!(!ignore_path_set.is_match(&FileName::Real(PathBuf::from("src/bar.rs"))));
-            }
-            _ => {}
-        };
+        if !is_nightly_channel!() {
+            // This test requires non-nightly
```
Comment (calebcartwright) [inline src/formatting/syntux/session/ignore_path.rs:50]: Nit, but want to avoid a confusing comment :wink: 
```suggestion
            // This test requires nightly
```

File: src/formatting/syntux/session/ignore_path.rs [hunk 3]
```diff
@@ -42,22 +42,48 @@ mod test {
...
+        let ignore_path_set = IgnorePathSet::from_ignore_list(&config.ignore()).unwrap();
+
+        assert!(ignore_path_set.is_match(&FileName::Real(PathBuf::from("src/foo.rs"))));
+        assert!(ignore_path_set.is_match(&FileName::Real(PathBuf::from("bar_dir/baz.rs"))));
+        assert!(!ignore_path_set.is_match(&FileName::Real(PathBuf::from("src/bar.rs"))));
+    }
+    #[test]
+    fn test_ignore_path_set_with_dir() {
+        if !is_nightly_channel!() {
+            // This test requires non-nightly
```
Comment (calebcartwright) [inline src/formatting/syntux/session/ignore_path.rs:64]:
```suggestion
            // This test requires nightly
```

Comment (sasurau4) [reply src/formatting/syntux/session/ignore_path.rs]: :scream:

**Comment by calebcartwright** [comment]
Awesome, thank you!
