### PR TITLE
fix Issue 4020: problem reformatting block comments

### LINKED ISSUE #4020: rustfmt keeps reformatting C-style doc comment
Using this version of `rustfmt`:

```
$ cargo +nightly fmt -- -V
rustfmt 1.4.11-nightly (18382352 2019-12-03)
```

and starting with this file:

```
/** foobar */
const foo: u32 = 0;
```

I find that `rustfmt` keeps adding asterisks to the end of the comment.  If I keep re-running `rustfmt`, I get more asterisks:

```
$ cat src/dummy.rs 
/** foobar */
const foo: u32 = 0;
$ cargo +nightly fmt -- src/dummy.rs 
$ cat src/dummy.rs 
/** foobar **/
const foo: u32 = 0;
$ cargo +nightly fmt -- src/dummy.rs 
$ cat src/dummy.rs 
/** foobar * **/
const foo: u32 = 0;
$ cargo +nightly fmt -- src/dummy.rs 
$ cat src/dummy.rs 
/** foobar * * **/
const foo: u32 = 0;
$ cargo +nightly fmt -- src/dummy.rs 
$ cat src/dummy.rs 
/** foobar * * * **/
const foo: u32 = 0;
$ cargo +nightly fmt -- src/dummy.rs 
$ cat src/dummy.rs 
/** foobar * * * * **/
const foo: u32 = 0;
$ cargo +nightly fmt -- src/dummy.rs 
$ cat src/dummy.rs 
/** foobar * * * * * **/
const foo: u32 = 0;
$ 
```

### PR DESCRIPTION
**Pull request by ahl**
Fixes #4020 

prior to the fix, the tests fail like this:
```
Mismatch at tests/source/issue-4020.rs:1:
 // rustfmt-wrap_comments: true
 
-/** foobar */
+/** foobar **/
 const foo1: u32 = 0;
 
 /**

Mismatch at tests/source/issue-4020.rs:7:
- * foobar
- */
+ ** foobar
+ **/
 const foo2: u32 = 0;
```

### CODE REVIEW

File: rustfmt-core/rustfmt-lib/tests/source/issue-4020.rs [hunk 1]
```diff
@@ -0,0 +1,9 @@
+// rustfmt-wrap_comments: true
+
```
Comment (calebcartwright) [inline rustfmt-core/rustfmt-lib/tests/source/issue-4020.rs]: I don't think it's mentioned in the Contributing docs, but for awareness, when the test is just ensuring rustfmt doesn't modify the formatting like this one you only need the test file under `target` and can skip the one under `source`

Comment (ahl) [reply rustfmt-core/rustfmt-lib/tests/source/issue-4020.rs]: Thanks for that! Removed now.

**Comment by davepacheco** [comment]
Thanks for the fix, @ahl!

It looks like this would fix #4020.  Are there any blockers for landing this change?

**Comment by calebcartwright** [comment]
> Are there any blockers for landing this change?

FWIW, no, I believe this is good to go. Just needs an approval from someone with merge perms. It'll likely be a while longer even after merge before this fix is released and available though due to the current release cycle for rustfmt.

**Comment by ahl** [comment]
@calebcartwright is there anything I can do to nudge it along?

**Comment by calebcartwright** [comment]
Unfortunately probably not @ahl. There's not a lot of folks on the rustfmt wg, and seems they've been very busy and unavailable recently. 

Thank you for the PR though, hopefully it won't be too much longer!

**Comment by ahl** [comment]
@topecongiro you merged #4079 -- would you mind taking a look at this one? Thanks.
