### PR TITLE
Fixed 'Comment removed between type name and =' issue

### LINKED ISSUE #4244: Comment removed between type name and =
```rust
pub type Export /*: Bound */ = S1;
```

This is one where I think a comment *is* justified; today we do not enforce such bounds (i.e. the compiler does not check that the right-hand side of a `type` definition actually conforms to such a bound), and the compiler actually errors if you try to include it (because we don't want people to mistakenly think that such bounds are enforced).

But the comment here serves a useful purpose (about the *intent*, that we intend for this type definition to conform to the bound).

_Originally posted by @pnkfelix in https://github.com/rust-lang/rustfmt/issues/2781#issuecomment-629384358_

### PR DESCRIPTION
**Pull request by whizsid**
Fixes #4244 .

### CODE REVIEW

File: src/formatting/items.rs [hunk 1]
```diff
@@ -1642,12 +1643,28 @@ fn rewrite_type<R: Rewrite>(
...
+                    context,
+                    &result,
+                    "=",
+                    between,
+                    comment_shape,
+                    true,
+                )?
+            }
+            _ => format!("{}{}=", result, if has_where { "" } else { " " }),
+        };
```
Comment (calebcartwright) [inline src/formatting/items.rs:1667]: I think you'll find this to produce incorrect formatting in cases where the ident is not the final element in the lhs. 

Adding a comment before the assignment operator from the previous assignment will illustrate this:

```rust
type A<'a: 'static, T: Ord + 'static>: Eq + PartialEq where T: 'static + Copy /* x */ = Vec<u8>;
```

This ties into my comment above about not accepting an arbitrary 'between" span as the function param that defers to callers to define the span. Once that's changed to the full item span, the correct between span for this particular instance can calculated (and encapsulated) within this function based on the presence/absence of other items.

It also makes it easier in the future to support not dropping comments between other things (like the `type` keyword and the ident e.g. `type /*abc*/ A = u8;`)

**Review by calebcartwright — COMMENTED** [review]
Thanks @whizsid! This is a good starting point but we'll need to iterate on it a bit to cover other scenarios. Inline feedback left for your review

**Comment by whizsid** [comment]
@calebcartwright Thank you for the revision. I changed my PR as you suggested. Can you kindly review it again?

File: src/formatting/items.rs [hunk 2]
```diff
@@ -1647,7 +1648,30 @@ fn rewrite_type<R: Rewrite>(
...
+                    .block_left(context.config.tab_spaces())?;
+
+                combine_strs_with_missing_comments(
+                    context,
+                    result.trim_end(),
+                    "=",
+                    comment_span,
+                    comment_shape,
+                    true,
+                )?
```
Comment (calebcartwright) [inline src/formatting/items.rs:1671]: We will want to use the `comment_shape` here for comments, but in cases where there's a where clause we don't want to for the assignment operator and the rhs. That's because in cases where the item has a `where` clause followed by a block or assignment the block/assignment is not supposed to be indented.

https://github.com/rust-dev-tools/fmt-rfcs/blob/master/guide/items.md#where-clauses

File: tests/target/issue-4244.rs [hunk 3]
```diff
@@ -0,0 +1,20 @@
...
+    = SS;
+
+pub trait D<T> {
+    type E /* Comment E */ = SS;
+}
+
+type F<'a: 'static, T: Ord + 'static>: Eq + PartialEq
+where
+    T: 'static + Copy, /* x */
+    = Vec<u8>;
```
Comment (calebcartwright) [inline tests/target/issue-4244.rs:20]: This is the case I was referring to above, it should be:

```suggestion
type F<'a: 'static, T: Ord + 'static>: Eq + PartialEq
where
    T: 'static + Copy, /* x */
= Vec<u8>;
```

File: tmp/test.rs [hunk 4]
```diff
@@ -0,0 +1,15 @@
+fn main() {
```
Comment (calebcartwright) [inline tmp/test.rs:1]: Could you remove this file, I'm guessing this was included in the commit by mistake :smile:

**Comment by calebcartwright** [comment]
Thank you!
