### PR TITLE
handle None case to remove whitespace before lhs

### LINKED ISSUE #3923: Rustfmt fails on trailing whitespace in long constant
This code, with a trailing space after the `=` gives
```
error[internal]: left behind trailing whitespace
 --> /playground/src/main.rs:1:1:18
  |
1 | const TEST: &str = 
  |                   ^
  |

warning: rustfmt has failed to format. See previous 1 errors.
```
```rust
const TEST: &str = 
    "1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111";
```

### PR DESCRIPTION
**Pull request by rchaser53**
fix #3923

### CODE REVIEW

File: src/items.rs [hunk 1]
```diff
@@ -1813,11 +1813,21 @@ fn rewrite_static(
...
             Shape::legacy(remaining_width, offset.block_only()),
         )
         .and_then(|res| recover_comment_removed(res, static_parts.span, context))
+        .or_else(|| {
+            let nested_indent = offset.block_indent(context.config);
+            let rhs = context.snippet(expr.span).trim();
+            Some(format!(
+                "{}{}{}",
+                lhs,
+                nested_indent.to_string_with_newline(context.config),
```
Comment (topecongiro) [inline src/items.rs]: We should add a newline only if the original code has a newline between `=` and the rhs so that we don't get a weird indentation on the rhs.

Comment (rchaser53) [reply src/items.rs]: Thank you for the review. I fixed it.
