### PR TITLE
Fix #5488 - prevent shorthand init for tuple struct

### LINKED ISSUE #5488: use_field_init_shorthand option breaks numbered struct field initialization
If I have a struct type with an implicit field such as
```
struct MyStruct(u64);
```
And I attempt to initialize it to 0
```
let instance = MyStruct { 0: 0 };
```
With the option "use_field_init_shorthand = true", rustfmt will incorrectly shorten the initialization to:
```
let instance = MyStruct { 0 };
```
This code will no longer compile after running rustfmt.

### PR DESCRIPTION
**Pull request by RajivTS**
Closes #5488

Fix for #5488. Before applying shorthand initialization for structs,
check if identifier is a literal (e.g. tuple struct). If yes, then do
not apply short hand initialization.

Added test case to validate the changes for the fix.

### CODE REVIEW

File: src/expr.rs [hunk 1]
```diff
@@ -1716,12 +1716,19 @@ pub(crate) fn rewrite_field(
...
+                    true
+                } else {
+                    false
+                };
+                if !is_lit && e.as_str() == name && context.config.use_field_init_shorthand() {
+                    Some(attrs_str + name)
+                } else {
+                    Some(format!("{}{}{}{}", attrs_str, name, separator, e))
+                }
             }
```
Comment (ytmimi) [inline src/expr.rs:1731]: Here's a suggestion to minimize the diff. We can check if the `expr.kind` is an `ast::ExprKind::Lit(_)` before we get to the match expression. Then we can just update the first match arm to include the additional check instead of pulling in the logic from the first and second match arms into one arm.

```rust
        let is_lit = matches!(expr.kind, ast::ExprKind::Lit(_));
        match expr {
            Some(ref e) if !is_lit && e.as_str() == name && context.config.use_field_init_shorthand() => {
                Some(attrs_str + name)
            }
            Some(e) => Some(format!("{}{}{}{}", attrs_str, name, separator, e)),
        }
        ...
```

File: tests/source/issue-5488.rs [hunk 2]
```diff
@@ -0,0 +1,11 @@
+// rustfmt-use_field_init_shorthand: true
+fn main() {
+    // Since MyStruct is a tuple struct, it should not be shorthanded to
+    // MyStruct { 0 } even if use_field_init_shorthand is enabled.
+    let instance = MyStruct { 0: 0 };
```
Comment (ytmimi) [inline tests/source/issue-5488.rs:5]: Whether MyStruct is a tuple struct or not isn't represented in the AST, and isn't obvious just by looking at the code snippet. Could you add the tuple struct definition for MyStruct before main to make it 100% clear that MyStruct is a tuple struct.

**Review by ytmimi — COMMENTED** [review]
Thanks for your first contribution to rustfmt 🎉

Check out some of the inline comments I left and let me know if anything is unclear!

File: src/expr.rs [hunk 3]
```diff
@@ -1716,9 +1716,11 @@ pub(crate) fn rewrite_field(
         let overhead = name.len() + separator.len();
         let expr_shape = shape.offset_left(overhead)?;
         let expr = field.expr.rewrite(context, expr_shape);
-
+        let is_lit = matches!((*field.expr).kind, ast::ExprKind::Lit(_));
```
Comment (ytmimi) [inline src/expr.rs:1719]: A minor nit, but could you rewrite this as:
```suggestion
        let is_lit = matches!(field.expr.kind, ast::ExprKind::Lit(_));
```

**Review by ytmimi — APPROVED** [review]
Thanks for your work on this! I think we're good to go here. Will hold off on merging to give @calebcartwright a chance to review.

**Review by calebcartwright — APPROVED** [review]
LGTM, thanks @RajivTS and apologies for both the delayed merge and my missing of your question back on #5488
