### PR TITLE
fix: properly wrap long `impl trait` function parameters

### LINKED ISSUE #6381: Too long line for function parameter of type impl Trait
Consider the following function:

```rust
fn my_function(
    my_long_impl_trait_parameter: impl Into<MyVeryLongTypeNameThatMakesThisWholeLineOverThe100CharLimit>,
) {
}
```

The parameter line is too long (105 chars) but `rustfmt` does not change it, it even reformats to this if we try to fix it manually.

Interestingly, if we add one more character then it breaks correctly:
```rust
fn my_function(
    my_long_impl_trait_parameter: impl Into<
        MyVeryLongTypeNameThatMakesThisWholeLineOverThe100CharLimitA,
    >,
) {
}
```
(I have chosen the example in the extreme case on purpose)

Also if we remove the `impl ` and replace `Into` with some struct name it correctly formats again. So I think it has to do with the `impl `, but this is just a wild guess.

### PR DESCRIPTION
**Pull request by ytmimi**
Fixes #6381 

Before we weren't taking the length of `impl ` into account so the trait thought it had more room than it actually did to format itself on a single line.

### CODE REVIEW

File: tests/target/issue_6381_style_edition_2024.rs
Comment (ytmimi) [inline tests/target/issue_6381_style_edition_2024.rs:1]: Show that the line doesn't wrap for `style-edition=2024`

File: tests/target/issue_6381_style_edition_2027.rs
Comment (ytmimi) [inline tests/target/issue_6381_style_edition_2027.rs:1]: Show that the line properly wraps for `style-edition=2027`

File: src/types.rs [hunk 1]
```diff
@@ -1016,9 +1016,14 @@ impl Rewrite for ast::Ty {
                 }
                 let rw = if context.config.style_edition() <= StyleEdition::Edition2021 {
                     it.rewrite_result(context, shape)
+                } else if context.config.style_edition() == StyleEdition::Edition2024 {
+                    join_bounds(context, shape, it, false)
                 } else {
+                    // 5 = 'impl `
+                    let shape = shape.offset_left(5, self.span())?;
```
Comment (jieyouxu) [inline src/types.rs]: Remark: I suppose one could also write

```rs
"impl ".chars().count()
```

```rs
"impl ".len() // same as above due to only-ASCII
```

But comment works too :D

**Review by jieyouxu — APPROVED** [review]
Looks good, thanks

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rustfmt/6798/53e39cceb48b5e42cbde66162895b6a2148be959..50dd8b52fe73bb82d319f4880b6b9b8d5e383770)*

File: src/types.rs (hunk 1 above)
Comment (ytmimi) [reply src/types.rs]: We've typically left comments in the code but I don't mind changing this to `"impl ".len()`.
