### PR TITLE
Fix: rustfmt should not remove inner attributes from inline const blocks

### LINKED ISSUE #6158: rustfmt removes inner attributes from inline const blocks
Clippy unfortunately warns about asserts whose conditions can be evaluated at compile-time even in inline const blocks. It's a [known issue](https://github.com/rust-lang/rust-clippy/issues/8159), it'll hopefully be solved at some point.

In the meantime, if one wishes to perform such compile-time asserts without disabling the lint globally, one can simply allow the offending lint:

```rust
fn main() {
    const {
        #![allow(clippy::assertions_on_constants)]

        assert!(1 < 2);
    }
}
```

Unfortunately, running rustfmt on the above will simply remove the attribute ([try it on the playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=cd1afc21b1eb34711d4ad0175658624f)), resulting in:

```rust
fn main() {
    const {
        assert!(1 < 2);
    }
}
```

And then Clippy nags at us again :'(

With inline const blocks due to being stabilized for 1.79 (in 6 weeks), it would be nice to fix rustfmt to not eat their code away.

### Meta

rustfmt version:
```
1.7.0-nightly (2024-05-03 d2d24e3)
```

### PR DESCRIPTION
**Pull request by WeiTheShinobi**
fixes #6158

`cargo test` 0 failed

first time contributed on this project🥳

### CODE REVIEW

File: src/expr.rs [hunk 1]
```diff
@@ -139,7 +139,14 @@ pub(crate) fn format_expr(
...
         ast::ExprKind::ConstBlock(ref anon_const) => {
-            Some(format!("const {}", anon_const.rewrite(context, shape)?))
+            if let ast::ExprKind::Block(ref block, label) = anon_const.value.kind {
+                Some(format!(
+                    "const {}",
+                    rewrite_block(block, Some(expr.attrs()), label, context, shape)?
+                ))
+            } else {
+                Some(format!("const {}", anon_const.rewrite(context, shape)?))
+            }
```
Comment (ytmimi) [inline src/expr.rs:149]: Instead of duplicating the `Some(format!("const {}"))` code in both branches, let's pull that out and save it for the end. I think a nice way to rewrite this would be something like this:

```rust
            let rewrite = match anon_const.value.kind {
                ast::ExprKind::Block(ref block, opt_label) => {
                    // Inner attributes are associated with the `ast::ExprKind::ConstBlock` node,
                    // not the `ast::Block` node we're about to rewrite. To prevent dropping inner
                    // attributes call `rewrite_block` directly.
                    // See https://github.com/rust-lang/rustfmt/issues/6158
                    rewrite_block(block, Some(&expr.attrs), opt_label, context, shape)?
                }
                _ => anon_const.rewrite(context, shape)?,
            };
            Some(format!("const {}", rewrite))
```

**Review by ytmimi — CHANGES_REQUESTED** [review]
Thanks for jumping in to work on this PR! With a few minor tweaks we should be good

**Review by ytmimi — APPROVED** [review]
Thanks for making the requested changes!

**Comment by ytmimi** [comment]
[Diff check job also passed](https://github.com/rust-lang/rustfmt/actions/runs/9326683863/job/25675955884) so we're good to go 👍🏼
