### PR TITLE
fix handling of newline_style conflicts

### LINKED ISSUE #3849: --check does not obey the newlines settings in rustfmt.toml
If you have a file with CRLF newlines and `newline_style = "Unix"` in `rustfmt.toml` or vice versa, then `cargo fmt -- --check` does not output any diff or exit with an error code.

Running `cargo fmt` itself updates the line endings as desired. `--check` seems to obey other settings in `rustfmt.toml`.

Occurs on both rustfmt 1.4.8-nightly (2019-10-04) and rustfmt 1.4.4-stable.

### PR DESCRIPTION
**Pull request by calebcartwright**
Fixes #3849 

There were two underyling issues with the way we were handling newline style differences that only surfaced when the source files have Windows style line feeds and/or when the `newline_style` config was set to `Windows`. 

Details inline below

### CODE REVIEW

File: src/emitter/diff.rs [hunk 1]
```diff
@@ -36,6 +36,13 @@ impl Emitter for DiffEmitter {
...
                 );
             }
+        } else if original_text != formatted_text {
+            // This occurs when the only difference between the original and formatted values
+            // is the newline style. This happens because The make_diff function compares the
+            // original and formatted values line by line, independent of line endings.
+            let file_path = ensure_real_path(filename);
+            writeln!(output, "Incorrect newline style in {}", file_path.display())?;
+            return Ok(EmitterResult { has_diff: true });
         }
```
Comment (calebcartwright) [inline src/emitter/diff.rs]: When running in `--check` mode, this is the emitter used, and like many of the other emitters, it leverages the `make_diff` function in [rustfmt_diff.rs](https://github.com/rust-lang/rustfmt/blob/master/src/rustfmt_diff.rs#L183).

That function internally leverages the [diff](https://crates.io/crates/diff) crate check for any formatting changes on a line by line basis. However, internally `diff` [leverages](https://github.com/utkarshkukreti/diff.rs/blob/master/src/lib.rs#L17-L35) the [str.lines()](https://doc.rust-lang.org/std/primitive.str.html#method.lines) function which ignores line endings. 

This ensures that `rustfmt --check ..` will exit with a non-zero exit code, even if the only change `rustfmt` would make is the newline style. I added a line to emit the name of the file if there was a newline style issue, because IMO it would be confusing if the only issue in my project was newline style and running `rustfmt --check` was giving me a non-zero exit code (due to the newline style diffs) without giving me any indication why.

File: src/source_file.rs [hunk 2]
```diff
@@ -65,15 +74,25 @@ where
...
+        fs::read_to_string(ensure_real_path(filename))?
+    } else {
+        match source_map
+            .and_then(|x| x.get_source_file(&filename.into()))
+            .and_then(|x| x.src.as_ref().map(ToString::to_string))
+        {
+            Some(ori) => ori,
+            None => fs::read_to_string(ensure_real_path(filename))?,
+        }
     };
```
Comment (calebcartwright) [inline src/source_file.rs]: This change is to resolve the other bug I found while working on the diff emitter. It turns out that internally, as the parser constructs the source map, all of the files loaded into the source map store a value of the original file contents with all line endings normalized to Unix style:

https://github.com/rust-lang/rust/blob/31d75c4e9c5318e880601d3c2cc71e5df094a120/src/libsyntax_pos/lib.rs#L1065-L1072

https://github.com/rust-lang/rust/blob/53b352edb6f441bc3cf5386806fcc4686f275130/src/libsyntax/source_map.rs#L223-L269

This means that even if the original file contents were using Windows style line endings, that the Source Map will **always** represent the SourceFile.src values with Unix style line endings. As mentioned in the PR description, this results in buggy behavior with `rustfmt` whenever Windows style line endings are involved (either in rustfmt `newline_style` config and/or in the original file contents). In such instances, it is necessary to read the original file contents from disk in order to get a "correct" value for `original_text`

I'm of two minds as to whether this change should be version gated (and/or should require an explicit config option), but I ended up settling with this because my thinking was that users that are explicitly overriding the default `newline_style` config value in `rustfmt` would definitely expect the behavior this change provides. 

Definitely open to any suggested changes/alternatives though!

File: src/emitter/diff.rs (hunk 1 above)
Comment (scampi) [reply src/emitter/diff.rs]: If `make_diff` use [str.split](https://doc.rust-lang.org/std/primitive.str.html#method.split) then this additional check wouldn't be needed ? The error message could be less clear though...

Comment (calebcartwright) [reply src/emitter/diff.rs]: Thanks @scampi! 

> If make_diff use str.split then this additional check wouldn't be needed ? The error message could be less clear though...

Just to clarify, are you asking if we could avoid this check here if we updated `make_diff` to include checking line endings? If so, then potentially yes, although that would result in the line ending characters always being displayed in the output when there's any diff. Also in the instance of newline style only diffs, I think it would most often result in `rustfmt` printing the entire contents of the file twice (for example if the original used `\r\n` and `rustfmt` changed the newline style to `\n`).

I could take a look into what would be involved to make that happen in `make_diff` if you'd like?
