### PR TITLE
Add test cases for fixed issues

### LINKED ISSUE #3068: Closing braces inside macros are double indented with hard tabs
rustfmt version: `rustfmt 0.99.5-nightly (90692a5 2018-09-26)`

When `hard_tabs` is off, it is formatted like this:
```rust

macro_rules! foo {
    ($bar: expr, $t: ty) => {
        $bar(|x| {
            if x {
                None
            }
            else {
                None
            }
        })
    };
}
```

When `hard_tabs` is on, it is formatted like this:
```rust
macro_rules! foo {
	($bar: expr, $t: ty) => {
		$bar(|x| {
			if x {
				None
				}
			else {
				None
				}
			})
	};
}
```

Closing braces have one more indentation when `hard_tabs` is on.

### LINKED ISSUE #3550: assert!() macro's formatting is unlike anything else
For some reason the assert!() macro is not following the normal formatting rules:

component is not on a new line and the final ); isn't either. Here's the playground repro by shepmaster: https://play.integer32.com/?version=stable&mode=debug&edition=2018&gist=ffd800255272b66f60170a907f1bc8e2

### LINKED ISSUE #3638: Wrapping at just over 100 chars for macro invocation
```rust
macro_rules! abait { ($x:expr) => { Ok(()) } }

mod a {
    fn foo() -> Result<(), ()> {
        unsafe {
            (
                abait!(proxy.load_account(ahc_client_end, TEST_ACCOUNT_ID.clone().as_mut().into()))?,
                (),
            )
        };
        Ok(())
    }
}
```
is the result of `rustfmt` with the default config, but it should be wrapping the `abait!` line. If `abait!` is replaced with a function `abaity`, `rustfmt` will wrap the line.

### LINKED ISSUE #3858: Macro body gets formatted weirdly
rustfmt formats this macro like this:
```rust
macro_rules! member_mut {
	($self:expr, $member:expr) => {{
		use self::Member::*;
		let r = &mut *$self;
		match $member {
			A => &mut r.a,
			B => &mut r.b,
			}
		}};
}
```
The closing braces are wrongly indented.

### LINKED ISSUE #3936: Incorrect indentation when using `return` in a macro
This macros is formatted using rustfmt:
```rust
macro_rules! m {
	($a:expr) => {
		if $a {
			return;
			}
	};
}
```
That closing curly bracket under the return clearly has to be one indented one level less.

Config used:
```toml
hard_tabs = true
use_small_heuristics = "Off"
```

### PR DESCRIPTION
**Pull request by ayazhafiz**
The cases with `hard_tabs: true` were fixed in 2836f9bd84a3f8bed96dc6aaa5e8cfd219171245.
Not sure about the rest, but this suggests a number of open issues are
already resolved.

Closes #3068
Closes #3550
Closes #3638
Closes #3858
Closes #3936

### CODE REVIEW

File: rustfmt-core/rustfmt-lib/tests/target/issue-3068.rs [hunk 1]
```diff
@@ -0,0 +1,15 @@
+// rustfmt-hard_tabs: true
+
+macro_rules! foo {
+	($bar: expr, $t: ty) => {
+		$bar(|x| {
+			if x {
+				None;
```
Comment (calebcartwright) [inline rustfmt-core/rustfmt-lib/tests/target/issue-3068.rs:7]: Let's remove the extra statement so this matches the snippet provided in the issue
```suggestion
```

File: rustfmt-core/rustfmt-lib/tests/target/issue-3068.rs [hunk 2]
```diff
@@ -0,0 +1,15 @@
...
+				None
+			} else {
+				None;
```
Comment (calebcartwright) [inline rustfmt-core/rustfmt-lib/tests/target/issue-3068.rs:10]: Ditto
```suggestion
```

File: rustfmt-core/rustfmt-lib/tests/target/issue-3550.rs [hunk 3]
```diff
@@ -0,0 +1,39 @@
+fn main() {
```
Comment (calebcartwright) [inline rustfmt-core/rustfmt-lib/tests/target/issue-3550.rs:1]: for #3550 i think it would be good to have a test under `source` that has the original snippet (plus something that gets formatted to the other snippet added here) and then here showing that formatted as expected

File: rustfmt-core/rustfmt-lib/tests/target/issue-3550.rs [hunk 4]
```diff
@@ -0,0 +1,39 @@
...
+            .long()
+            .long()
+            .long()
+            .long()
+            .long()
+            .long()
+            .long()
+            .long()
+            .long(),
+    );
```
Comment (calebcartwright) [inline rustfmt-core/rustfmt-lib/tests/target/issue-3550.rs:38]: What's this second one validating that's not covered by the first one?

File: rustfmt-core/rustfmt-lib/tests/target/issue-3068.rs (hunk 1 above)
Comment (ayazhafiz) [reply rustfmt-core/rustfmt-lib/tests/target/issue-3068.rs:7]: Done. Keeping the semicolon so that we force the block; otherwise, the macro will wrap into one line.

File: rustfmt-core/rustfmt-lib/tests/target/issue-3550.rs (hunk 3 above)
Comment (ayazhafiz) [reply rustfmt-core/rustfmt-lib/tests/target/issue-3550.rs:1]: Done

File: rustfmt-core/rustfmt-lib/tests/target/issue-3550.rs (hunk 4 above)
Comment (ayazhafiz) [reply rustfmt-core/rustfmt-lib/tests/target/issue-3550.rs:38]: The first is a function, the second is the assert! macro. Per #3550 we want to see that assert! is formatted similar to regular function calls.

Comment (calebcartwright) [reply rustfmt-core/rustfmt-lib/tests/target/issue-3550.rs:38]: ha! and that's why reviewing PRs when half asleep isn't a great idea :smile:

File: rustfmt-core/rustfmt-lib/tests/target/issue-3068.rs (hunk 1 above)
Comment (calebcartwright) [reply rustfmt-core/rustfmt-lib/tests/target/issue-3068.rs:7]: Could we use `single_line_if_else_max_width` instead? Want to keep it as close to the original issue as possible
```
// rustfmt-single_line_if_else_max_width: 10
```

Comment (ayazhafiz) [reply rustfmt-core/rustfmt-lib/tests/target/issue-3068.rs]: yep, fixed

Comment (calebcartwright) [reply rustfmt-core/rustfmt-lib/tests/target/issue-3068.rs]: thanks! will merge once CI jobs finish
