### PR TITLE
Resolve some minor parsing bugs

### LINKED ISSUE #4418: failed to parse Real("...")
**Describe the bug**

This message sometimes (but not always) appears at the bottom of output after a parse error. It seems unintentional and maybe like some accidental debug logging.

```console
$  target/release/rustfmt src/openbrace.rs 
error: this file contains an unclosed delimiter
 --> /git/rustfmt/src/openbrace.rs:1:3
  |
1 | {
  | - ^
  | |
  | unclosed delimiter

error: expected item, found `{`
 --> /git/rustfmt/src/openbrace.rs:1:1
  |
1 | {
  | ^ expected item

failed to parse Real("/git/rustfmt/src/openbrace.rs")

$  target/release/rustfmt src/closebrace.rs 
error: unexpected closing delimiter: `}`
 --> /git/rustfmt/src/closebrace.rs:1:1
  |
1 | }
  | ^ unexpected closing delimiter

$  ▎
```

**To Reproduce**

Build rustfmt from master branch (currently 6646248ffce9741a748bc8f5aa25dec0d85ccb17). Write `{` to openbrace.rs and `}` to closebrace.rs. Run rustfmt on each as shown above. `failed to parse Real("...")` appears for openbrace.rs, though not for closebrace.rs. It should be for neither.

**Expected behavior**

Just the compiler-style diagnostics would be sufficient. `failed to parse Real("...")` should not appear also at the end.

### LINKED ISSUE #4431: Error writing files: failed to resolve mod on missing semicolon
**Describe the bug**

`rustfmt` returns
```
Error writing files: failed to resolve mod `error`: cannot parse <project dir>/src/error.rs
```

**To Reproduce**

`src/main.rs`:

```rust
mod error;

fn main() {}
```

`src/error.rs`:

```rust
pub struct S // missing semicolon
```

**Meta**

- rustfmt version: `rustfmt 1.4.21-nightly (01f2eadc 2020-09-04)`
- From where did you install rustfmt?: `rustup`
- How do you run rustfmt: `cargo fmt`

### PR DESCRIPTION
**Pull request by calebcartwright**
This address a couple minor parsing bugs, notably an uncaught rustc parser panic that was only triggered with certain inputs in the main/root file, some poor rustfmt parsing error message, and a spurious parser diagnostic cancel instead of emission.

Fixes #4418 
Fixes #4431

### CODE REVIEW

File: src/formatting/syntux/parser.rs [hunk 1]
```diff
@@ -77,14 +80,18 @@ impl<'a> ParserBuilder<'a> {
...
+                new_parser_from_file(sess, file, None)
+            }))
+            .map_err(|_| None),
             Input::Text(text) => rustc_parse::maybe_new_parser_from_source_str(
                 sess,
                 rustc_span::FileName::Custom("stdin".to_owned()),
                 text,
-            ),
+            )
+            .map_err(|db| Some(db)),
```
Comment (calebcartwright) [inline src/formatting/syntux/parser.rs:94]: I'm not terribly thrilled about Option-wrapping the error diagnostics to address this, but since `new_parser_from_file` doesn't return a Result and will instead panic this seemed like the least invasive/intensive way to resolve the bug

File: src/result.rs [hunk 2]
```diff
@@ -118,7 +118,7 @@ pub enum OperationError {
     #[error("invalid glob pattern found in ignore list: {0}")]
     InvalidGlobPattern(ignore::Error),
     /// Parse error occurred while parsing the input.
-    #[error("failed to parse {input:?}")]
+    #[error("failed to parse {input}")]
```
Comment (calebcartwright) [inline src/result.rs:121]: This fixes the `failed to parse Real("...")` error detail that was reported in the linked issue to instead display the correct error (e.g. `failed to parse /home/caleb/dev/rustfmt-sandbox/bad-syntax/src/openbrace.rs` and `failed to parse <stdin>` for stdin)

**Comment by calebcartwright** [comment]
Going to go ahead and merge as the changes are pretty trivial and can always be refactored should a better solution present itself :smile:

**Comment by topecongiro** [comment]
Apologies for the late review; all the changes look good to me. Thank you!
