### PR TITLE
fix: Add parenthesis around `..` closure if it's a method call receiver

### LINKED ISSUE #4808: Rustfmt breaks method call on || ..
**Describe the bug**

Working input code:

```rust
trait Trait {
    fn method(&self);
}

impl<F: Fn() -> T, T> Trait for F {
    fn method(&self) {}
}

fn main() {
    || .. .method();
}
```

Rustfmt diff as of current master (292c0cc6b59863c9769b9aaa3470da4fb3ddf7d4):

```diff
-     || .. .method();
+     || ...method();
```

The transformed code produced by rustfmt fails to compile.

```console
error: unexpected token: `...`
  --> src/main.rs:10:8
   |
10 |     || ...method();
   |        ^^^
   |
help: use `..` for an exclusive range
   |
10 |     || ..method();
   |        ^^
help: or `..=` for an inclusive range
   |
10 |     || ..=method();
   |        ^^^

error[E0425]: cannot find function `method` in this scope
  --> src/main.rs:10:11
   |
10 |     || ...method();
   |           ^^^^^^ not found in this scope
```

**To Reproduce**

Run rustfmt on playground or locally. Try to compile code. https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=f76a649e0bd1b99cbebc46c711ca9bf5

**Expected behavior**

I would expect compilable output, either unchanged `|| .. .method()` or parenthesized `(|| ..).method()`.

**Meta**

- rustfmt version: rustfmt 2.0.0-rc.2-dev (292c0cc6 2021-04-20)
- From where did you install rustfmt?: built from source
- How do you run rustfmt: `rustfmt src.rs`

### PR DESCRIPTION
**Pull request by Centri3**
Fixes #4808

I think this is (perhaps?) okay without a version gate as the formatted code would be invalid before now, might be wrong though ^^

### CODE REVIEW

File: src/chains.rs [hunk 1]
```diff
@@ -254,10 +254,16 @@ impl ChainItemKind {
...
                                 &expr.kind,
                                 ast::ExprKind::Lit(lit) if crate::expr::lit_ends_in_dot(lit)
-                            ),
+                            ) || matches!(
+                                &expr.kind,
+                                ast::ExprKind::Closure(ref cl) if matches!(
+                                    cl.body.kind,
+                                    ast::ExprKind::Range(None, None, ast::RangeLimits::HalfOpen),
+                                )
+                            )),
```
Comment (fee1-dead) [inline src/chains.rs:266]: Could this be extracted to a method? I would prefer if this is pulled to a separate function that uses `match` instead of `matches`.

**Comment by fee1-dead** [comment]
Also, I think a similar case should also be fixed:

```rust

trait Trait {
    fn method(&self) {}
}

impl Trait for f32 {}

pub fn x() {
    || 10. .method();
}

```

and where the expression is a range that has a start:

```rust


trait Trait {
    fn method(&self);
}

impl<F: Fn() -> T, T> Trait for F {
    fn method(&self) {}
}

pub fn x() {
    || 1.. .method();
}
```

therefore this shouldn't just match on `|| ..` specifically, but perhaps with an abstraction similar to `lit_ends_in_dot` used above but for expressions

File: tests/target/issue-4808.rs [hunk 2]
```diff
@@ -0,0 +1,13 @@
...
+}
+
+impl<F: Fn() -> T, T> Trait for F {}
+
+impl Trait for f32 {}
+
+fn main() {
+    || (10.).method();
+    (|| ..).method();
+    (|| 1..).method();
```
Comment (ytmimi) [inline tests/target/issue-4808.rs:12]: Are the parens being applied in the correct place in the first example? Shouldn't it be `(|| 10.).method();` if we're applying the method to the closure?

Comment (fee1-dead) [reply tests/target/issue-4808.rs:12]: It should be correct iirc. This is just one of the weird precedence things

**Review by fee1-dead — APPROVED** [review]

File: tests/target/issue-4808.rs (hunk 2 above)
Comment (ytmimi) [reply tests/target/issue-4808.rs:12]: I just checked and here are the ASTs that rustfmt sees when parsing

```rust
fn main() {
    || (10.).method();
}
```

<details>
<summary>AST wrapping float in parens</summary>
<pre>
Module {
    ast_mod_kind: None,
    items: [
        Item {
            attrs: [],
            id: NodeId(4294967040),
            span: Span {
                lo: BytePos(
                    0,
                ),
                hi: BytePos(
                    36,
                ),
                ctxt: #0,
            },
            vis: Visibility {
                kind: Inherited,
                span: Span {
                    lo: BytePos(
                        0,
                    ),
                    hi: BytePos(
                        0,
                    ),
                    ctxt: #0,
                },
                tokens: None,
            },
            ident: main#0,
            kind: Fn(
                Fn {
                    defaultness: Final,
                    generics: Generics {
                        params: [],
                        where_clause: WhereClause {
                            has_where_token: false,
                            predicates: [],
                            span: Span {
                                lo: BytePos(
                                    9,
                                ),
                                hi: BytePos(
                                    9,
                                ),
                                ctxt: #0,
                            },
                        },
                        span: Span {
                            lo: BytePos(
                                7,
                            ),
                            hi: BytePos(
                                7,
                            ),
                            ctxt: #0,
                        },
                    },
                    sig: FnSig {
                        header: FnHeader {
                            unsafety: No,
                            asyncness: No,
                            constness: No,
                            ext: None,
                        },
                        decl: FnDecl {
                            inputs: [],
                            output: Default(
                                Span {
                                    lo: BytePos(
                                        10,
                                    ),
                                    hi: BytePos(
                                        10,
                                    ),
                                    ctxt: #0,
                                },
                            ),
                        },
                        span: Span {
                            lo: BytePos(
                                0,
                            ),
                            hi: BytePos(
                                9,
                            ),
                            ctxt: #0,
                        },
                    },
                    body: Some(
                        Block {
                            stmts: [
                                Stmt {
                                    id: NodeId(4294967040),
                                    kind: Semi(
                                        Expr {
                                            id: NodeId(4294967040),
                                            kind: Closure(
                                                Closure {
                                                    binder: NotPresent,
                                                    capture_clause: Ref,
                                                    constness: No,
                                                    asyncness: No,
                                                    movability: Movable,
                                                    fn_decl: FnDecl {
                                                        inputs: [],
                                                        output: Default(
                                                            Span {
                                                                lo: BytePos(
                                                                    19,
                                                                ),
                                                                hi: BytePos(
                                                                    19,
                                                                ),
                                                                ctxt: #0,
                                                            },
                                                        ),
                                                    },
                                                    body: Expr {
                                                        id: NodeId(4294967040),
                                                        kind: MethodCall(
                                                            MethodCall {
                                                                seg: PathSegment {
                                                                    ident: method#0,
                                                                    id: NodeId(4294967040),
                                                                    args: None,
                                                                },
                                                                receiver: Expr {
                                                                    id: NodeId(4294967040),
                                                                    kind: Paren(
                                                                        Expr {
                                                                            id: NodeId(4294967040),
                                                                            kind: Lit(
                                                                                Lit {
                                                                                    kind: Float,
                                                                                    symbol: "10.",
                                                                                    suffix: None,
                                                                                },
                                                                            ),
                                                                            span: Span {
                                                                                lo: BytePos(
                                                                                    20,
                                                                                ),
                                                                                hi: BytePos(
                                                                                    23,
                                                                                ),
                                                                                ctxt: #0,
                                                                            },
                                                                            attrs: [],
                                                                            tokens: None,
                                                                        },
                                                                    ),
                                                                    span: Span {
                                                                        lo: BytePos(
                                                                            19,
                                                                        ),
                                                                        hi: BytePos(
                                                                            24,
                                                                        ),
                                                                        ctxt: #0,
                                                                    },
                                                                    attrs: [],
                                                                    tokens: None,
                                                                },
                                                                args: [],
                                                                span: Span {
                                                                    lo: BytePos(
                                                                        25,
                                                                    ),
                                                                    hi: BytePos(
                                                                        33,
                                                                    ),
                                                                    ctxt: #0,
                                                                },
                                                            },
                                                        ),
                                                        span: Span {
                                                            lo: BytePos(
                                                                19,
                                                            ),
                                                            hi: BytePos(
                                                                33,
                                                            ),
                                                            ctxt: #0,
                                                        },
                                                        attrs: [],
                                                        tokens: None,
                                                    },
                                                    fn_decl_span: Span {
                                                        lo: BytePos(
                                                            16,
                                                        ),
                                                        hi: BytePos(
                                                            18,
                                                        ),
                                                        ctxt: #0,
                                                    },
                                                    fn_arg_span: Span {
                                                        lo: BytePos(
                                                            16,
                                                        ),
                                                        hi: BytePos(
                                                            18,
                                                        ),
                                                        ctxt: #0,
                                                    },
                                                },
                                            ),
                                            span: Span {
                                                lo: BytePos(
                                                    16,
                                                ),
                                                hi: BytePos(
                                                    33,
                                                ),
                                                ctxt: #0,
                                            },
                                            attrs: [],
                                            tokens: None,
                                        },
                                    ),
                                    span: Span {
                                        lo: BytePos(
                                            16,
                                        ),
                                        hi: BytePos(
                                            34,
                                        ),
                                        ctxt: #0,
                                    },
                                },
                            ],
                            id: NodeId(4294967040),
                            rules: Default,
                            span: Span {
                                lo: BytePos(
                                    10,
                                ),
                                hi: BytePos(
                                    36,
                                ),
                                ctxt: #0,
                            },
                            tokens: None,
                            could_be_bare_literal: false,
                        },
                    ),
                },
            ),
            tokens: None,
        },
    ],
    inner_attr: [],
    span: Span {
        lo: BytePos(
            0,
        ),
        hi: BytePos(
            37,
        ),
        ctxt: #0,
    },
}
</pre>
</details>

```rust
fn main() {
    (|| 10.).method();
}
```

<details>
<summary>AST wrapping closure in parens</summary>
<pre>
Module {
    ast_mod_kind: None,
    items: [
        Item {
            attrs: [],
            id: NodeId(4294967040),
            span: Span {
                lo: BytePos(
                    0,
                ),
                hi: BytePos(
                    36,
                ),
                ctxt: #0,
            },
            vis: Visibility {
                kind: Inherited,
                span: Span {
                    lo: BytePos(
                        0,
                    ),
                    hi: BytePos(
                        0,
                    ),
                    ctxt: #0,
                },
                tokens: None,
            },
            ident: main#0,
            kind: Fn(
                Fn {
                    defaultness: Final,
                    generics: Generics {
                        params: [],
                        where_clause: WhereClause {
                            has_where_token: false,
                            predicates: [],
                            span: Span {
                                lo: BytePos(
                                    9,
                                ),
                                hi: BytePos(
                                    9,
                                ),
                                ctxt: #0,
                            },
                        },
                        span: Span {
                            lo: BytePos(
                                7,
                            ),
                            hi: BytePos(
                                7,
                            ),
                            ctxt: #0,
                        },
                    },
                    sig: FnSig {
                        header: FnHeader {
                            unsafety: No,
                            asyncness: No,
                            constness: No,
                            ext: None,
                        },
                        decl: FnDecl {
                            inputs: [],
                            output: Default(
                                Span {
                                    lo: BytePos(
                                        10,
                                    ),
                                    hi: BytePos(
                                        10,
                                    ),
                                    ctxt: #0,
                                },
                            ),
                        },
                        span: Span {
                            lo: BytePos(
                                0,
                            ),
                            hi: BytePos(
                                9,
                            ),
                            ctxt: #0,
                        },
                    },
                    body: Some(
                        Block {
                            stmts: [
                                Stmt {
                                    id: NodeId(4294967040),
                                    kind: Semi(
                                        Expr {
                                            id: NodeId(4294967040),
                                            kind: MethodCall(
                                                MethodCall {
                                                    seg: PathSegment {
                                                        ident: method#0,
                                                        id: NodeId(4294967040),
                                                        args: None,
                                                    },
                                                    receiver: Expr {
                                                        id: NodeId(4294967040),
                                                        kind: Paren(
                                                            Expr {
                                                                id: NodeId(4294967040),
                                                                kind: Closure(
                                                                    Closure {
                                                                        binder: NotPresent,
                                                                        capture_clause: Ref,
                                                                        constness: No,
                                                                        asyncness: No,
                                                                        movability: Movable,
                                                                        fn_decl: FnDecl {
                                                                            inputs: [],
                                                                            output: Default(
                                                                                Span {
                                                                                    lo: BytePos(
                                                                                        20,
                                                                                    ),
                                                                                    hi: BytePos(
                                                                                        20,
                                                                                    ),
                                                                                    ctxt: #0,
                                                                                },
                                                                            ),
                                                                        },
                                                                        body: Expr {
                                                                            id: NodeId(4294967040),
                                                                            kind: Lit(
                                                                                Lit {
                                                                                    kind: Float,
                                                                                    symbol: "10.",
                                                                                    suffix: None,
                                                                                },
                                                                            ),
                                                                            span: Span {
                                                                                lo: BytePos(
                                                                                    20,
                                                                                ),
                                                                                hi: BytePos(
                                                                                    23,
                                                                                ),
                                                                                ctxt: #0,
                                                                            },
                                                                            attrs: [],
                                                                            tokens: None,
                                                                        },
                                                                        fn_decl_span: Span {
                                                                            lo: BytePos(
                                                                                17,
                                                                            ),
                                                                            hi: BytePos(
                                                                                19,
                                                                            ),
                                                                            ctxt: #0,
                                                                        },
                                                                        fn_arg_span: Span {
                                                                            lo: BytePos(
                                                                                17,
                                                                            ),
                                                                            hi: BytePos(
                                                                                19,
                                                                            ),
                                                                            ctxt: #0,
                                                                        },
                                                                    },
                                                                ),
                                                                span: Span {
                                                                    lo: BytePos(
                                                                        17,
                                                                    ),
                                                                    hi: BytePos(
                                                                        23,
                                                                    ),
                                                                    ctxt: #0,
                                                                },
                                                                attrs: [],
                                                                tokens: None,
                                                            },
                                                        ),
                                                        span: Span {
                                                            lo: BytePos(
                                                                16,
                                                            ),
                                                            hi: BytePos(
                                                                24,
                                                            ),
                                                            ctxt: #0,
                                                        },
                                                        attrs: [],
                                                        tokens: None,
                                                    },
                                                    args: [],
                                                    span: Span {
                                                        lo: BytePos(
                                                            25,
                                                        ),
                                                        hi: BytePos(
                                                            33,
                                                        ),
                                                        ctxt: #0,
                                                    },
                                                },
                                            ),
                                            span: Span {
                                                lo: BytePos(
                                                    16,
                                                ),
                                                hi: BytePos(
                                                    33,
                                                ),
                                                ctxt: #0,
                                            },
                                            attrs: [],
                                            tokens: None,
                                        },
                                    ),
                                    span: Span {
                                        lo: BytePos(
                                            16,
                                        ),
                                        hi: BytePos(
                                            34,
                                        ),
                                        ctxt: #0,
                                    },
                                },
                            ],
                            id: NodeId(4294967040),
                            rules: Default,
                            span: Span {
                                lo: BytePos(
                                    10,
                                ),
                                hi: BytePos(
                                    36,
                                ),
                                ctxt: #0,
                            },
                            tokens: None,
                            could_be_bare_literal: false,
                        },
                    ),
                },
            ),
            tokens: None,
        },
    ],
    inner_attr: [],
    span: Span {
        lo: BytePos(
            0,
        ),
        hi: BytePos(
            37,
        ),
        ctxt: #0,
    },
}
</pre>
</details>

And here's the diff when comparing wrapping the float vs wrapping the closure. For reference I saved both ASTs to files and ran `git --no-pager diff --no-index wrap_float_with_parens_ast.txt wrap_closure_with_parens_ast.txt`

From the AST level it seems that the first is treated as a closure that contains a method call, while the second is a method call on a tuple.
<details>
<summary>AST Diff</summary>

```diff
Module {
                                     kind: Semi(
                                         Expr {
                                             id: NodeId(4294967040),
-                                            kind: Closure(
-                                                Closure {
-                                                    binder: NotPresent,
-                                                    capture_clause: Ref,
-                                                    constness: No,
-                                                    asyncness: No,
-                                                    movability: Movable,
-                                                    fn_decl: FnDecl {
-                                                        inputs: [],
-                                                        output: Default(
-                                                            Span {
-                                                                lo: BytePos(
-                                                                    19,
-                                                                ),
-                                                                hi: BytePos(
-                                                                    19,
-                                                                ),
-                                                                ctxt: #0,
-                                                            },
-                                                        ),
+                                            kind: MethodCall(
+                                                MethodCall {
+                                                    seg: PathSegment {
+                                                        ident: method#0,
+                                                        id: NodeId(4294967040),
+                                                        args: None,
                                                     },
-                                                    body: Expr {
+                                                    receiver: Expr {
                                                         id: NodeId(4294967040),
-                                                        kind: MethodCall(
-                                                            MethodCall {
-                                                                seg: PathSegment {
-                                                                    ident: method#0,
-                                                                    id: NodeId(4294967040),
-                                                                    args: None,
-                                                                },
-                                                                receiver: Expr {
-                                                                    id: NodeId(4294967040),
-                                                                    kind: Paren(
-                                                                        Expr {
+                                                        kind: Paren(
+                                                            Expr {
+                                                                id: NodeId(4294967040),
+                                                                kind: Closure(
+                                                                    Closure {
+                                                                        binder: NotPresent,
+                                                                        capture_clause: Ref,
+                                                                        constness: No,
+                                                                        asyncness: No,
+                                                                        movability: Movable,
+                                                                        fn_decl: FnDecl {
+                                                                            inputs: [],
+                                                                            output: Default(
+                                                                                Span {
+                                                                                    lo: BytePos(
+                                                                                        20,
+                                                                                    ),
+                                                                                    hi: BytePos(
+                                                                                        20,
+                                                                                    ),
+                                                                                    ctxt: #0,
+                                                                                },
+                                                                            ),
+                                                                        },
+                                                                        body: Expr {
                                                                             id: NodeId(4294967040),
                                                                             kind: Lit(
                                                                                 Lit {
@@ -148,58 +148,58 @@ Module {
                                                                             attrs: [],
                                                                             tokens: None,
                                                                         },
-                                                                    ),
-                                                                    span: Span {
-                                                                        lo: BytePos(
-                                                                            19,
-                                                                        ),
-                                                                        hi: BytePos(
-                                                                            24,
-                                                                        ),
-                                                                        ctxt: #0,
+                                                                        fn_decl_span: Span {
+                                                                            lo: BytePos(
+                                                                                17,
+                                                                            ),
+                                                                            hi: BytePos(
+                                                                                19,
+                                                                            ),
+                                                                            ctxt: #0,
+                                                                        },
+                                                                        fn_arg_span: Span {
+                                                                            lo: BytePos(
+                                                                                17,
+                                                                            ),
+                                                                            hi: BytePos(
+                                                                                19,
+                                                                            ),
+                                                                            ctxt: #0,
+                                                                        },
                                                                     },
-                                                                    attrs: [],
-                                                                    tokens: None,
-                                                                },
-                                                                args: [],
+                                                                ),
                                                                 span: Span {
                                                                     lo: BytePos(
-                                                                        25,
+                                                                        17,
                                                                     ),
                                                                     hi: BytePos(
-                                                                        33,
+                                                                        23,
                                                                     ),
                                                                     ctxt: #0,
                                                                 },
+                                                                attrs: [],
+                                                                tokens: None,
                                                             },
                                                         ),
                                                         span: Span {
                                                             lo: BytePos(
-                                                                19,
+                                                                16,
                                                             ),
                                                             hi: BytePos(
-                                                                33,
+                                                                24,
                                                             ),
                                                             ctxt: #0,
                                                         },
                                                         attrs: [],
                                                         tokens: None,
                                                     },
-                                                    fn_decl_span: Span {
-                                                        lo: BytePos(
-                                                            16,
-                                                        ),
-                                                        hi: BytePos(
-                                                            18,
-                                                        ),
-                                                        ctxt: #0,
-                                                    },
-                                                    fn_arg_span: Span {
+                                                    args: [],
+                                                    span: Span {
                                                         lo: BytePos(
-                                                            16,
+                                                            25,
                                                         ),
                                                         hi: BytePos(
-                                                            18,
+                                                            33,
                                                         ),
                                                         ctxt: #0,
                                                     },

```

</details>

If there are compilation steps that happen after parsing that ensures that `|| (10.).method();` means "apply the method call to the return value of the closure then I think we're good to go, otherwise I'd like to change the output to produce `(|| 10.).method();` for consistency, and because I think that `(|| 10.).method();` more clearly conveys that we're applying the method to the returned value of the closure.

Comment (Centri3) [reply tests/target/issue-4808.rs:12]: I believe we aren't applying it to the closure in specific, but the float, for some reason the previous `lit_ends_in_dot` check didn't apply here.

Changing it to `(|| 10.).method()` applies it to the closure, which causes differing behavior (and can cause compile errors if the trait isn't implemented for closures)

Comment (ytmimi) [reply tests/target/issue-4808.rs:12]: Yeah, I just double checked and it turns out that the code highlighted in the first example of https://github.com/rust-lang/rustfmt/pull/5842#issuecomment-1640533057 (inlined below for reference)

```rust
trait Trait {
    fn method(&self) {}
}

impl Trait for f32 {}

pub fn x() {
    || 10. .method();
}
```

parses as a closure and the the method is applied to the `10.`

while the second example from that comment (inlined below for reference) parses as method call where the receiver is a closure.

```rust
trait Trait {
    fn method(&self);
}

impl<F: Fn() -> T, T> Trait for F {
    fn method(&self) {}
}

pub fn x() {
    || 1.. .method();
}
```

**Review by ytmimi — APPROVED** [review]
After double checking that we're adding parentheses to the right places I think we're ready to merge. @Centri3 when you have a moment can you rebase these changes on the latest master.
