### PR TITLE
Fixed comment formatting issue between assignment operator and rhs

### LINKED ISSUE #4427: rustfmt fails to remove trailing whitespace when next line is a comment before value
**Describe the bug**

`cargo fmt` fails with:

```
error[internal]: left behind trailing whitespace
 --> /tmp/cargo-fmt-fail/src/lib.rs:1:1:16
  |
1 | const A: usize = 
  |                 ^
  |

warning: rustfmt has failed to format. See previous 1 errors.
```

**To Reproduce**

Copy and paste this into a new source file (note the trailing whitespace in first line):
```rust
const A: usize = 
    // Some constant
    2;
```

**Expected behavior**

**Meta**

- rustfmt version: rustfmt 1.4.18-stable (8157a3f 2020-07-15)
- From where did you install rustfmt?: rustup
- How do you run rustfmt: `cargo fmt`, `rustfmt`

### PR DESCRIPTION
**Pull request by whizsid**
Fixes #4427 . 

I tried to use `combine_strs_with_missing_comments` in `rewrite_assign_rhs_with`. But it is a huge change and already fixed it in some places using boiler plates. So I didn't take that approach.

### CODE REVIEW

**Comment by calebcartwright** [comment]
Thanks so much for the PR @whizsid! I've only had a chance to do a quick glance through this, will try to set aside some time in the next couple days to go through in detail.

One initial thought I had is that I still think it would be good if we could have a more generic/reusable approach for handling assignments that have comments between the lhs and rhs. The existing util functions are pretty clear that they expect lhs to (inclusively) end with the assignment operator, but it feels like we keep solving these situations by peeking into the rhs and attaching the comments between the assignment op and the rhs to the _lhs_ because these util functions are dropping those comments. This has almost certainly resulted in some duplicated efforts throughout the codebase. 

What if we created a new function (something along the lines of `rewrite_assign_rhs_with_comments`) that was basically the same as `rewrite_assign_rhs_with` but would take some additional params, like the "between" span (the one between the assignment op and the expr lo), perhaps the RHS tactics, and anything else it needed so that it could actually be responsible to incorporating these comments.

The logic conditions would be basically the same as what I gathered you were doing here, though do keep in mind that it's preferable if rustfmt can preserve comment-associated line breaks so

```rust
const B: usize =   
/*    Some constant */
3;
```
would ideally be formatted as 
```rust
const B: usize =   
    /*    Some constant */
    3;
```

while
```rust
const C :   usize   
      = /* foo */5;
```
would be:
```rust
const C: usize = /* foo */ 5;
```

(this is where `combine_strs_with_missing_comments` really shines!)

Think we should be able to achieve that pretty easily solely within this new function by:
* check if there's a comment (and if so newlines) within the "between" snippet, and if so block indent the shape
* get the rhs via the same `rewrite_assign_rhs_expr` process just like `rewrite_assign_rhs_with` currently does
* if there were no comments then can return the same Some(lhs + rhs)
* otherwise return `combine_strs_with_missing_comments` with a trimming of the start of rhs (since `combine_strs_with_missing_comments` will take care of this)

Then the only other change needed to fix the static item bug would be to switch the call from `rewrite_assign_rhs` to this new `rewrite_assign_rhs_with_comments` function (or whatever this hypothetical function would be named), and pass it the span between the `=` and expr lo.

What do you think?

**Comment by whizsid** [comment]
@calebcartwright It is a really good idea to implement a new function. I faced a problem when implementing it. `choose_rhs` is always prepending whitespace. I have trimmed the start of `rhs`. But it is not an idiomatic way.

**Comment by calebcartwright** [comment]
> choose_rhs is always prepending whitespace. I have trimmed the start of rhs. But it is not an idiomatic way.

Could you elaborate on what you mean? There's quite a lot of trimming done within rustfmt, both start and end, in various places to ensure proper formatting and alignment, so I'd push back against calling the usage of a trim function as non-idiomatic. 

That being said, ideally we wouldn't prepend the leading space on the rhs unnecessarily in the first place only to peel it off later (though again there's quite a few instances of this type of workflow within rustfmt). It'd take quite a bit of additional refactoring to be able to achieve that goal though, so I'd prefer to defer that to future PRs.

File: src/formatting/expr.rs [hunk 1]
```diff
@@ -1985,6 +1948,28 @@ pub(crate) fn rewrite_assign_rhs_with<S: Into<String>, R: Rewrite>(
...
+
+    let comment = context.snippet_provider.span_to_snippet(between)?;
+    if comment.trim().starts_with("/") {
+        let rhs = rhs.trim_start();
+
+        combine_strs_with_missing_comments(context, &lhs, &rhs, between, comment_shape, false)
+    } else {
+        Some(lhs + &rhs)
+    }
+}
```
Comment (calebcartwright) [inline src/formatting/expr.rs:1971]: Remember that the rhs isn't always going to be a lit, so if we have an inbetween comment then we should probably go ahead and use an updated shape to pass to `rewrite_assign_rhs_expr`

Consider this for example:
```rust
const B: usize =    // baz
            /* ba */
 {  3  
 // foo   
    };
```

We know that the start of the expression is going to end up on the next line due to the inbetween comments with newlines, but the rhs was still formatted with the original shape and (incorrectly) thinks that the opening brace will end up on the same line as the lhs.

What about tweaking what you have a bit to something like this:
```suggestion
    let lhs = lhs.into();
    let contains_comment = contains_comment(context.snippet(between_span));
    let shape = if contains_comment {
        shape.block_left(context.config.tab_spaces())?
    } else {
        shape
    };
    let rhs = rewrite_assign_rhs_expr(context, &lhs, ex, shape, rhs_tactics)?;
    
    if contains_comment {
        combine_strs_with_missing_comments(context, &lhs, &rhs, between, comment_shape, *new_param_or_true*)
    } else {
        Some(lhs + &rhs)
    }
}
```

File: src/formatting/expr.rs [hunk 2]
```diff
@@ -2008,6 +1993,7 @@ fn choose_rhs<R: Rewrite>(
                 .indent
                 .block_indent(context.config)
                 .to_string_with_newline(context.config);
+
```
Comment (calebcartwright) [inline src/formatting/expr.rs:1996]: I don't have a strong opinion one way or the other about whether there should be a newline here, though as a general comment, it's better to avoid such changes in unmodified parts of a PR in the future unless there's a really good reason for updating an unrelated section.

My guess is that this was just an accidental left over from an earlier pass at a solution that _did_ make some changes down here, so no worries!

File: tests/source/issue-4427.rs [hunk 3]
```diff
@@ -0,0 +1,10 @@
+const A: usize = 
+  // Some constant
+    2;
+
+const B: usize =   
+/* constant */
+3;
+
+const C :   usize   
+      = /* foo */5;
```
Comment (calebcartwright) [inline tests/source/issue-4427.rs:10]: Let's add a few more test scenarios just to cover some additional bases. It doesn't necessarily need to be these exact snippets (though certainly can be!) just as long as the same scenarios are included.

```suggestion
      = /* foo */5;
      
      const D: usize =    // baz
/*    Some constant */
            /* ba */
 {  3  
 // foo   
    };

const E:   usize=             /* foo */5;

const F: usize =
{
        7
    };

const G: usize = /* foooooooooooooooooooooooooooooooooooooooooooooooooooooooo0000000000000000xx00 */ 5;
                  const H: usize = /* asdfasdf */ match G > 1 {
                    true => 1,
                    false => 3,
                };
            
                pub static FOO_BAR: Vec<u8> =    //f
                {
                    vec![]};
```

**Review by calebcartwright — COMMENTED** [review]
Awesome, thank you @whizsid. The approach definitely seems like it'll work and the PR is in pretty good shape! Couple minor inline changes requested along with a few additional test scenarios, but should be good to merge after those are addressed

**Comment by whizsid** [comment]
@calebcartwright I have changed the code as you guided. Can you review it again?

**Comment by calebcartwright** [comment]
Awesome, thanks so much!
