### PR TITLE
fix(rustfmt): fix struct field formatting with doc comments present

### LINKED ISSUE #5215: Tuple struct field comments consume the field itself, only with doc comment
### Describe the bug

When using the sequence `/// doc comment`, `// regular comment`, \<field definition\> within a tuple struct definition, rustfmt joins the field with the regular comment above, removing the field from the struct definition.

#### Input

```
struct MyTuple(
    /// Doc Comments
    // TODO note to add more to Doc Comments
    u32,
);
```

#### Output - correctness issue
```
struct MyTuple(
    /// Doc Comments
    // TODO note to add more to Doc Commentsu32,
);
```

The same applies for `/* block comments */`, but in this case the issue is purely cosmetic (does not change the struct definition).

#### Input (block comment)

```
struct MyTuple(
    /// Doc Comments
    /* TODO note to add more to Doc Comments */
    u32,
);
```

#### Output (block comment) - cosmetic issue

```
struct MyTuple(
    /// Doc Comments
    /* TODO note to add more to Doc Comments */u32,
);
```
At the very least, I expect there to be a separating space between the block comment and the `u32`, similar to the [similar example with no doc comment](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=56caf79accd720ea8602769218ff5c73)
```diff
-    /* TODO note to add more to Doc Comments */u32,
+    /* TODO note to add more to Doc Comments */ u32,
```

### Working cases

However, this issue doesn't seem to appear when the `/// doc comment` is removed, nor in named-field structs:

* No doc comment - **works as expected**
    ```
    struct MyTuple(
        // TODO note to add more to Doc Comments
        u32,
    );
    ```
* Struct with named fields (non-tuple) - **works as expected**
    ```
    struct MyStruct {
        /// Doc Comments
        // TODO note to add more to Doc Comments
        field: u32,
    }
    ```

### To Reproduce

* Tuple struct with doc comment, single line comment (broken) - [Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=38b7784b0a617a94a79cda0ae39f8aed)
* Tuple struct with doc comment, block comment (broken, cosmetic only) - [Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=666959c08b89aaf6e603877f44c7c085)
* Tuple struct with single line comment, only (**not broken**, just for comparison) - [Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=34fc4198daa2989a861645b1219c5345)
* Struct (named fields) with doc comment, single line comment (**not broken,** just for comparison) - [Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=d59605361c61150ac05d0b354a5bbf56)

### Expected behavior

I expect rustfmt to never change the tuple struct definition (`MyStruct(u32)` --> `MyStruct()`), and also preserve cosmetic newlines in the block comment case.

### Meta

* rustfmt version: rustfmt 1.4.38-nightly (2022-02-02 27f5d83)
* From where did you install rustfmt?: using playground only
* How do you run rustfmt: using playground only

### Additional remarks
* I didn't find any existing issues matching this problem description, but #4643 may be similar.
* One of my first issues reported to rustfmt. Let me know if this is not actually a bug.

### PR DESCRIPTION
**Pull request by tharun208**
Fixes #5215

### CODE REVIEW

File: tests/target/configs/struct_field_align_threshold/20.rs [hunk 1]
```diff
@@ -43,7 +43,7 @@ pub struct Foo {
     #[AnAttribute]
     g:     SomeOtherType,
     /// A doc comment on a field
-    h:     AThirdType,
+    h: AThirdType,
```
Comment (ytmimi) [inline tests/target/configs/struct_field_align_threshold/20.rs:46]: When possible we want to avoid messing with unrelated tests. I think in this case we don't want to lose the alignment.

Comment (tharun208) [reply tests/target/configs/struct_field_align_threshold/20.rs:46]: sure

**Review by ytmimi — CHANGES_REQUESTED** [review]
Thanks for submitting this PR!

A few minor tweaks, and then I think we should be good to go on this one.

File: src/items.rs [hunk 2]
```diff
@@ -1733,7 +1733,7 @@ pub(crate) fn rewrite_struct_field(
         .offset_left(overhead + spacing.len())
         .and_then(|ty_shape| field.ty.rewrite(context, ty_shape));
     if let Some(ref ty) = orig_ty {
-        if !ty.contains('\n') {
+        if !ty.contains('\n') && !contains_comment(&attr_prefix) {
```
[the remark this answers is not in the document]
Comment (tharun208) [reply src/items.rs]: thanks and fixed it

**Comment by ytmimi** [comment]
Thanks again for taking on the PR, and for the quick turnaround after receiving some feedback! CI checks look like they're off to a good start, but I'll check back up on this later for another review.

**Comment by ytmimi** [comment]
The code changes look good to me!

I'm wondering if we could add another test case around an attribute that isn't necessarily a doc comment. For example, what does this get formatted to?

```rust
struct MyTuple(
    #[cfg(unix)] // some comment
    u64,
    #[cfg(not(unix))] /*block comment */
    u32,
);

struct MyTuple(
    #[cfg(unix)]
    // some comment
    u64,
    #[cfg(not(unix))]
    /*block comment */
    u32,
);
```

File: tests/target/structs.rs [hunk 3]
```diff
@@ -356,3 +356,31 @@ where
...
+
+// #5215
+struct MyTuple(
+    #[cfg(unix)]
+    // some comment
+    u64,
+    #[cfg(not(unix))]
+    // block comment
+    u32,
+);
```
Comment (ytmimi) [inline tests/target/structs.rs:386]: Thanks again for adding these additional tests! On closer inspection of the tests it strikes me as odd that the block comments are changed to inline comments. I understand this is happening becuase this file sets``// rustfmt-normalize_comments: true``.

I think it would be nicer to isolate these tests. Would it be possible to move these tests to ``tests/target/issue_5215.rs`` and ``tests/source/issue_5215.rs``. Feel free to use a different name for the file, just want to make sure we highlight the link between these tests and the corresponding issue.

**Comment by ytmimi** [comment]
@tharun208 Thanks again for all the work on this. I know there's a been a decent amount of back and forth so far.

For completeness, and to improve the test coverage could you take all of the tuple struct tests and also include regular struct versions of them. For the regular struct versions of the tests could you also add some fields with various visibility modifiers like ``pub`` or ``pub(crate)`` in combination with block and inline comments and doc attributes and normal attributes?

**Comment by tharun208** [comment]
@ytmimi sorry for replying late. will improve the coverage and possibly come with the changes next week.

**Comment by ytmimi** [comment]
@tharun208 absolutely no worries. I totally get that things come up and working on PRs can get away from you. No rush on the requested tests, but if you have time to work on them next that would be great!

**Comment by tharun208** [comment]
@ytmimi can we merge this and introduce the test changes as a new pr?

**Comment by ytmimi** [comment]
> @ytmimi can we merge this and introduce the test changes as a new pr?

I personally don't have an issue with that, and I think the current tests show that the fix works, but just to give you an example these were the additional test cases that I was looking for: 

```rust
struct MyTuple(
    #[cfg(unix)] // some comment
    u64,
    #[cfg(not(unix))] /*block comment */
    u32,
);

struct MyTuple(
    #[cfg(unix)] // some comment
    pub u64,
    #[cfg(not(unix))] /*block comment */
    pub(crate) u32,
);

struct MyTuple(
    /// Doc Comments
    /* TODO note to add more to Doc Comments */
    pub u32,
    /// Doc Comments
    // TODO note
    pub(crate) u64,
);

struct MyTuple(
    /// Doc Comments
    /* TODO note to add more to Doc Comments */
    u32,
    /// Doc Comments
    // TODO note
    u64,
);

struct MyStruct {
    #[cfg(unix)] // some comment
    a: u64,
    #[cfg(not(unix))] /*block comment */
    b: u32,
}

struct MyStruct {
    #[cfg(unix)] // some comment
    pub a: u64,
    #[cfg(not(unix))] /*block comment */
    pub(crate) b: u32,
}

struct MyStruct {
    /// Doc Comments
    /* TODO note to add more to Doc Comments */
    a: u32,
    /// Doc Comments
    // TODO note
    b: u64,
}

struct MyStruct {
    /// Doc Comments
    /* TODO note to add more to Doc Comments */
    pub a: u32,
    /// Doc Comments
    // TODO note
    pub(crate) b: u64,
}
```

**Review by ytmimi — CHANGES_REQUESTED** [review]
Just one minor tweak to reintroduce a newline at the of `test/souce/structs.rs`, and I think we're good to go here!

**Comment by tharun208** [comment]
@ytmimi done 😃

**Review by ytmimi — APPROVED** [review]
LGTM Thanks for this!

**Review by calebcartwright — APPROVED** [review]
lgtm as well, thank you both!
