### PR TITLE
fix async expression indentation

### LINKED ISSUE #3765: await operator on async block gets unexpected indentation
Using the latest nightly, this:

```rust
async {
    // Do
    // some
    // work
}.await;
```

Gets formatted to this:

```rust
async {
    // Do
    // some
    // work
}
    .await;
```

I would expect it to either stay in place (because `}.await;` isn't really a long line) or move one line done, but without the indentation.

### PR DESCRIPTION
**Pull request by calebcartwright**
Resolves #3765 and adds explicit arms for each ast exp. node

### CODE REVIEW

File: src/utils.rs [hunk 1]
```diff
@@ -466,7 +466,27 @@ pub(crate) fn is_block_expr(context: &RewriteContext<'_>, expr: &ast::Expr, repr
         ast::ExprKind::Lit(_) => {
             repr.contains('\n') && trimmed_last_line_width(repr) <= context.config.tab_spaces()
         }
-        _ => false,
+        ast::ExprKind::Async(..) => true,
```
Comment (topecongiro) [inline src/utils.rs]: Actually, on second thought, this is not quite right because `async` block could be written in a single line. We should move this to the guard as `ast::ExprKind::Block(..)` and alike. Sorry that what I said in the issue comment was incorrect.

```diff
        ast::ExprKind::Mac(..)
        | ast::ExprKind::Call(..)
        | ast::ExprKind::MethodCall(..)
        | ast::ExprKind::Array(..)
        | ast::ExprKind::Struct(..)
        | ast::ExprKind::While(..)
        | ast::ExprKind::If(..)
        | ast::ExprKind::Block(..)
+        | ast::ExprKind::Async(..)
        | ast::ExprKind::Loop(..)
        | ast::ExprKind::ForLoop(..)
        | ast::ExprKind::Match(..) => repr.contains('\n'),
```

File: src/utils.rs [hunk 2]
```diff
@@ -466,7 +466,27 @@ pub(crate) fn is_block_expr(context: &RewriteContext<'_>, expr: &ast::Expr, repr
...
+        | ast::ExprKind::Continue(..)
+        | ast::ExprKind::Err
+        | ast::ExprKind::Field(..)
+        | ast::ExprKind::InlineAsm(..)
+        | ast::ExprKind::Let(..)
+        | ast::ExprKind::Path(..)
+        | ast::ExprKind::Range(..)
+        | ast::ExprKind::Repeat(..)
+        | ast::ExprKind::Ret(..)
+        | ast::ExprKind::TryBlock(..)
```
Comment (topecongiro) [inline src/utils.rs]: I think that `TryBlock` should be considered as block-like expression as well.

**Comment by topecongiro** [comment]
Thanks for the update!
