### PR TITLE
fix: imports_granularity module with path containing self

### LINKED ISSUE #4681: `imports_granularity = "Module"` causes compile error when path contains `self`
**Describe the bug**

If a path contains `self`, this keyword must be enclosed in braces:

```rust
use crate::lexer::{self}; // valid
use crate::lexer::self;   // invalid
```

rustfmt with `imports_granularity = "Module"` sometimes splits `use` statements so that invalid code like above is emitted.

**To Reproduce**

```rust
use crate::lexer::{self, tokens::TokenData};
```

rustfmt formats it like this:

```rust
use crate::lexer::self;
use crate::lexer::tokens::TokenData;
```

When formatting the file again, the `::self` is removed.

**Expected behavior**

rustfmt should emit the following code without having to run it twice:

```rust
use crate::lexer;
use crate::lexer::tokens::TokenData;
```

Note that `use crate::lexer;` and `use crate::lexer::{self};` are not actually equivalent: The latter only imports the `lexer` module, while the former looks in all namespaces, so it can import up to 3 items at once, e.g. a function, a module and a macro of the same name.

To make sure that the behaviour doesn't change, it needs to be formatted like so:

```rust
use crate::lexer::{self};
use crate::lexer::tokens::TokenData;
```

However, I would find this rather annoying, because of the way rust-analyzer handles auto-imports.

**Meta**

- rustfmt version: rustfmt 1.4.34-nightly (ea268b9 2021-01-28)
- From where did you install rustfmt?: rustup
- How do you run rustfmt: `cargo fmt`

### PR DESCRIPTION
**Pull request by tommilligan**
Closes #4681

(unintentionally) ports #4716 from `rustfmt-2.0.0-rc.2` to `master`, with some additional refactoring.

It looks like this issue was already fixed, but was then lost in the `rustfmt-2.0.0-rc.2` branch on this commit: https://github.com/rust-lang/rustfmt/commit/0e908555273391bc3aba087abae72791451fd84a

I implemented this separately but came up with a satisfyingly similar implementation - I've read the review comments on the original PR, so I don't think there should be much to add, but do let me know if anything needs changing!

### CODE REVIEW

**Comment by tommilligan** [comment]
Moves towards stabilising `imports_granularity` #4991

**Comment by calebcartwright** [comment]
Thanks so much! Will try to get to this shortly

File: src/imports.rs [hunk 1]
```diff
@@ -190,14 +190,18 @@ pub(crate) fn merge_use_trees(use_trees: Vec<UseTree>, merge_by: SharedPrefix) -
...
                 .find(|tree| tree.share_prefix(&flattened, merge_by))
             {
                 tree.merge(&flattened, merge_by);
             } else {
-                result.push(flattened);
+                // If this is the first tree with this prefix, handle potential trailing ::self
+                if merge_by == SharedPrefix::Module {
+                    flattened = flattened.nest_trailing_self();
+                }
+                result.push(flattened.nest_trailing_self());
```
Comment (calebcartwright) [inline src/imports.rs:204]: Is it necessary to make this nest call in the non-module case, and twice for the module case?

If so could you add or point to a test case that demonstrates why?

**Review by calebcartwright — COMMENTED** [review]
Thank you! LGTM overall, with one inline question for you

File: src/imports.rs (hunk 1 above)
Comment (tommilligan) [reply src/imports.rs]: Nope, that's definitely unnecessary, good spot. I added the conditional `merge_by` check later, I just forgot to remove the unconditional case.

Squashed and updated, ready for review again.

**Comment by calebcartwright** [comment]
Excellent, thank you!
