### PR TITLE
fix: between span derivation on cast exprs

### LINKED ISSUE #4534: Rustfmt regression: produces duplicated subexpressions and unparseable output involving `as` casts
Bisects to 6646248ffce9741a748bc8f5aa25dec0d85ccb17 (#4406).

### To reproduce:

```console
$ echo 'fn main() { let z = (x as f64 / y as f64).floor() as usize; }' | CFG_RELEASE_CHANNEL=dev CFG_RELEASE=1.48.0 cargo +nightly-2020-09-16 run --bin rustfmt --features rustfmt
```

Against the parent commit of 6646248ffce9741a748bc8f5aa25dec0d85ccb17 (correct output):

```rust
fn main() {
    let z = (x as f64 / y as f64).floor() as usize;
}
```

Against 6646248ffce9741a748bc8f5aa25dec0d85ccb17, and all the way through current master (17d90cab3005fcd20eedd1a6d91caa2e146f465c as of filing):

```rust
fn main() {
    let z = (x as f64 / y as f64).floor() as f64 / y as f64).floor()
        as f64 / y as f64).floor() as usize;
}
```

```console
error: unexpected closing delimiter: `)`
 --> src/main.rs:3:26
  |
3 |         as f64 / y as f64).floor() as usize;
  |                          ^ unexpected closing delimiter

error: mismatched closing delimiter: `)`
 --> src/main.rs:2:60
  |
1 | fn main() {
  |           - unclosed delimiter
2 |     let z = (x as f64 / y as f64).floor() as f64 / y as f64).floor()
  |                                                            ^ mismatched closing delimiter
```

### PR DESCRIPTION
**Pull request by calebcartwright**
Fixes #4534

### CODE REVIEW

File: src/formatting/expr.rs [hunk 1]
```diff
@@ -236,10 +236,10 @@ pub(crate) fn format_expr(
             /* Retrieving the comments before and after cast */
             let prefix_span = mk_sp(
                 subexpr.span.hi(),
-                context.snippet_provider.span_before(expr.span, "as"),
+                context.snippet_provider.span_before_last(expr.span, "as") - BytePos(1),
```
Comment (calebcartwright) [inline src/formatting/expr.rs:239]: Think there's a separate bug in this util function that only backs the position off by one, but feels like it should be the length of the needle. Our needle is the `as` keyword, so moving it back by one to avoid snagging the `a` in the keyword
