### PR TITLE
fix newline width calc in combine w/ comments

### LINKED ISSUE #4031: @ binding reformatted strangely on rustfmt from rustc 1.41.0-beta.4
The following line is formatting differently and in an undesirable way with rustfmt from rustc beta (1.41.0-beta.4):

https://github.com/yeslogic/allsorts/blob/c78fb470ca2a575570543918cfbf15422b0377b2/tests/woff2.rs#L236

The diff looks like this:

```diff
Diff in /home/travis/build/yeslogic/allsorts/tests/woff2.rs at line 233:
             .iter()
             .map(|glyph| match glyph {
                 GlyfRecord::Parsed(
-                    found @ Glyph {
+                    found
+                    @
+                    Glyph {
                         data: GlyphData::Composite { .. },
                         ..
                     },
```

### PR DESCRIPTION
**Pull request by calebcartwright**
Resolves #4031, refs #4110 

This address the binding formatting in #4110, but doesn't include any updates for the sub pattern formatting

### CODE REVIEW

File: rustfmt-core/rustfmt-lib/src/comment.rs [hunk 1]
```diff
@@ -188,7 +188,7 @@ pub(crate) fn combine_strs_with_missing_comments(
     let missing_comment = rewrite_missing_comment(span, shape, context)?;
 
     if missing_comment.is_empty() {
-        if allow_extend && prev_str.len() + first_sep.len() + next_str.len() <= shape.width {
+        if allow_extend && one_line_width <= shape.width {
```
Comment (calebcartwright) [inline rustfmt-core/rustfmt-lib/src/comment.rs:191]: I assume this is indeed a fix and that we don't want to use the full length of `next_str`. Otherwise `next_str` can start to exceed the shape width pretty quickly. 

For example:
```rust
fn foo() {
    match glyph {
        found @ Glyph {
            data: Gl::Com { .. },
            foo: bar,
        } => (),
        _ => (),
    };
}
```

Remains unchanged by rustfmt, but adding a few more items to the struct (or longer names) will increase the total `next_str` length and fail the conditional check resulting in a newline insertion.

```rust
fn foo() {
    match glyph {
        found @ Glyph {
            data: Gl::Com { .. },
            foo: bar,
            baz: qux,
        } => (),
        _ => (),
    };
}
```
would be reformatted to the below without this change
```rust
fn foo() {
    match glyph {
        found
        @
        Glyph {
            data: Gl::Com { .. },
            foo: bar,
            baz: qux,
        } => (),
        _ => (),
    };
}
```
