### PR TITLE
Do not modify original source code inside macro call

### LINKED ISSUE #3004: Running cargo fmt seems to break some macro expansion
Running cargo fmt on [Plume-org/Plume](https://github.com/Plume-org/Plume) breaks it. It seems to remove curly braces around the macro invocation, which make macro expansion fail with `unexpected end of macro invocation`

Step to reproduce :
```sh
$ git clone https://github.com/Plume-org/Plume
$ cd Plume
$ cargo check #compile fine
$ cargo fmt --all
$ cargo check #fail
```
Reproducible with `rustfmt 0.8.2-nightly (5e59925 2018-07-02)` (specified by `rust-toolchain`) and `rustfmt 0.99.2-nightly (5c9a2b6 2018-08-07)` via `+nightly`

### PR DESCRIPTION
**Pull request by topecongiro**
Closes #3004.

### CODE REVIEW

File: src/types.rs [hunk 1]
```diff
@@ -583,7 +583,13 @@ impl Rewrite for ast::Ty {
                 let is_dyn = tobj_syntax == ast::TraitObjectSyntax::Dyn;
                 // 4 is length of 'dyn '
                 let shape = if is_dyn { shape.offset_left(4)? } else { shape };
-                let res = bounds.rewrite(context, shape)?;
+                let mut res = bounds.rewrite(context, shape)?;
+                // We may have falsely removed a trailing `+` inside macro call.
+                if context.inside_macro() && bounds.len() == 1 {
```
Comment (scampi) [inline src/types.rs]: What part of the code removes the `+` character ? Sorry, I don't understand also why `stringify!((foo+));` is considered as a trait object.
Is it possible to have, e.g., `stringify!((foo-));` as well ? If so, it feels like this is a very specific fix that won't resolve other similar instances.

Comment (scampi) [reply src/types.rs]: ah ok! thanks for the explanation.

**Comment by nrc** [comment]
Thanks! And sorry I missed so much over Christmas and New Year - was having a break.
