### PR TITLE
Do not remove fn headers (e.g., async) on extern fn items

### LINKED ISSUE #4288: Async gets removed from extern blocks.
**Describe the bug**

The `async` keyword is removed when used inside an `extern "C"` block.

Currently this is not valid in Rust, because in C there are no async functions. But when using `wasm-bindgen` it is processes from a macro, and the functions are actually Javascript, not C, and there there are JS promises. Anyway, even if it is not valid, the keyword should not be removed while formatting.

**To Reproduce**

Format the following code:
```rust
extern "C" {
    async fn foo();
}
```
And see how the `async` keword disappears.

**Expected behavior**

It should keep the `async` keyword.

**Meta**

- rustfmt version: 1.4.15-beta (530eadf 2020-06-02)
- From where did you install rustfmt?: Rustup
- How do you run rustfmt: From console: `rustfmt --edition 2018 test.rs`

### PR DESCRIPTION
**Pull request by topecongiro**
Close #4288.

### CODE REVIEW

File: src/formatting/items.rs [hunk 1]
```diff
@@ -235,18 +235,18 @@ pub(crate) struct FnSig<'a> {
 
 impl<'a> FnSig<'a> {
     pub(crate) fn new(
```
Comment (ayazhafiz) [inline src/formatting/items.rs:237]: I think it may be easier to use `from_method_sig`, which allows for dropping this method entirely. See  https://github.com/rust-lang/rustfmt/pull/4290/files

Comment (topecongiro) [reply src/formatting/items.rs]: Good point! I like this idea better than mine. Thank you for creating the PR, and no worries about the duplicated work. GitHub UI is laggy these days.

**Comment by calebcartwright** [comment]
You both jumped on that one fast :smile:

File: src/formatting/items.rs (hunk 1 above)
Comment (calebcartwright) [reply src/formatting/items.rs]: Related aside, we should probably rename `from_method_sig` to `from_fn_sig`. Believe that's one that we missed when incorporating the upstream rustc Method -> Fn renaming
