### PR TITLE
Fixed semicolon getting moved into trait method comment

### LINKED ISSUE #4646: Rustfmt breaks trait method when where clause is commented out
In short, if you comment out the where clause, then the subsequent semicolon is moved into the comment.

Which of course breaks the code.

**Before:**

```rust
trait Foo {
    fn bar(&self)
    // where
    //     Self: Bar
    ;
}
```

**After:**

```rust
trait Foo {
    fn bar(&self)
    // where
    //     Self: Bar;
}
```

-----

rustfmt 1.4.25-stable (0f29ff6d 2020-11-11)

### PR DESCRIPTION
**Pull request by vallentin**
Fixes #4646

Thought the issue I encountered would be straightforward to fix, so I decided to give it a go.

Fixed by inserting a newline while maintaining current indentation, if the result of `rewrite_fn_base` ends in a comment.

### CODE REVIEW

File: src/formatting/items.rs [hunk 1]
```diff
@@ -434,6 +434,11 @@ impl<'a> FmtVisitor<'a> {
             FnBraceStyle::None,
         )?;
 
+        // If `result` ends with a comment, then remember to add a newline
+        if last_line_contains_single_line_comment(&result) {
+            result.push_str(&indent.to_string_with_newline(context.config));
+        }
```
Comment (calebcartwright) [inline src/formatting/items.rs:440]: I may be remembering incorrectly, but I believe the second item in the tuple from `rewrite_fn_base` is a boolean that informs consumers whether a newline is needed, and that internal check includes `last_line_contains_single_line_comment`. 

If so then we should just use that tuple element instead of tossing it and re-running the comment check

**Review by calebcartwright — COMMENTED** [review]
Thanks! Believe there's an opportunity to simplify this a bit more but please lmk if you think the suggested alternative isn't viable for some reason

File: src/formatting/items.rs (hunk 1 above)
Comment (vallentin) [reply src/formatting/items.rs:440]: I already tried that actually. But `force_new_line` is `true` in other cases, that would break existing test cases

For instance, if I replaced it with `if force_new_line` as returned by the second tuple item from `rewrite_fn_base`, then e.g. the [`max_width.rs`] test case would break, and result in:

[`max_width.rs`]: tests/source/configs/space_before_fn_sig_paren/max_width.rs

```rust
trait Story {
    fn swap_context<T: 'static + Context + Send + Sync>(&mut self, context: T) -> Option<Box<Context + Send + Sync>>
    ;
}
```

Instead of remain as:

```rust
trait Story {
    fn swap_context<T: 'static + Context + Send + Sync>(&mut self, context: T) -> Option<Box<Context + Send + Sync>>;
}
```

Comment (calebcartwright) [reply src/formatting/items.rs:440]: Gotcha, makes sense. If the current `rewrite_fn_base` newline_force check includes this same comment check, could we refactor the returned tuple to include a third element that also has result of that comment check, and then use that here (instead of the current second item)? Trying to avoid running the same comment check twice if possible

If that's not feasible then I think this will be fine, as it's not exactly expensive

Comment (vallentin) [reply src/formatting/items.rs:440]: I did consider that as well, but I was unsure if changing the signature of `rewrite_fn_base` was acceptable. I've just refactored it, and introduced a third item in the tuple.

Comment (calebcartwright) [reply src/formatting/items.rs:440]: > I've just refactored it, and introduced a third item in the tuple.

Great, thanks!

> I was unsure if changing the signature of rewrite_fn_base was acceptable.

Absolutely acceptable. We do publish rustfmt as a lib so there's some strict constraints on the public portions of the API, but for anything internal we can and do change whenever needed

**Review by calebcartwright — APPROVED** [review]
