### PR TITLE
Fix issue 'double spaces between struct field prefix and identity when using long attributes

### LINKED ISSUE #4671: Double Space between `pub &` when preceeded by long attribute
**Describe the bug**

Formatting this code places two spaces between `pub` and `&`.

```rust
struct X<'a>(
    #[X(X = "_________________________________________________________________________")]
    pub  &'a u32,
    // ^^
);
```

**Expected behavior**

The usual formatting is `pub &'a u32` (single space). I would expect rustfmt to stay consistent. Removing the attribute, shortening it, or turning it into a comment all lead to the single space formatting.

**Meta**

- rustfmt 1.4.25-stable (0f29ff6 2020-11-11)
- rustfmt 1.4.30-nightly (acd9486 2020-12-20)
- rustfmt 1.4.32-nightly (2021-01-16 216a643) (playground)
- From where did you install rustfmt? rustup, playground
- How do you run rustfmt: cargo fmt, playground, VSCode

### PR DESCRIPTION
**Pull request by whizsid**
Fixes #4671 .

### CODE REVIEW

File: src/formatting/items.rs [hunk 1]
```diff
@@ -1816,7 +1816,7 @@ pub(crate) fn rewrite_struct_field(
 
     let is_prefix_empty = prefix.is_empty();
     // We must use multiline. We are going to put attributes and a field on different lines.
-    let field_str = rewrite_assign_rhs(context, prefix, &*field.ty, shape)?;
+    let field_str = rewrite_assign_rhs(context, prefix.trim_end(), &*field.ty, shape)?;
     // Remove a leading white-space from `rewrite_assign_rhs()` when rewriting a tuple struct.
     let field_str = if is_prefix_empty {
         field_str.trim_start()
```
Comment (calebcartwright) [inline src/formatting/items.rs:1822]: I'm a little worried about unintentional side effects here. I think the real issue is that there's an assumption in this function that tuple struct fields will have no prefix (visibility, etc.) which obviously doesn't always pan out. I'd rather just add an additional branch between this current if and else which checks the end and beginning of the prefix and initial field_str respectively, and if both contain a space then just trim one of them.

what do you think?

File: tests/source/issue-4671.rs [hunk 2]
```diff
@@ -0,0 +1,11 @@
+struct X<'a>(
+    #[X(X = "_________________________________________________________________________")]
+    pub &'a u32,
+    // ^^
+);
```
Comment (calebcartwright) [inline tests/source/issue-4671.rs:5]: Could you add a snippet to this file that includes one that starts with the double space too?

**Review by calebcartwright — COMMENTED** [review]
Thanks for the PR! Looks like you've definitely zeroed in on the problem area, though I'd like to tweak the fix a bit

File: src/formatting/items.rs (hunk 1 above)
Comment (calebcartwright) [reply src/formatting/items.rs:1822]: Actually, I was wrong about this sorry. The real triggering scenario is an ident-less struct field which has some public/crate visibility and the formatted type cannot fit on the same line :upside_down_face: 

As such we do indeed want to drop any trailing space off the end, since the util function used isn't expecting the lhs to have one, good catch!

File: tests/source/issue-4671.rs (hunk 2 above)
Comment (calebcartwright) [reply tests/source/issue-4671.rs:5]: Would've been a nice to have but not necessary, will go ahead and merge

**Comment by calebcartwright** [comment]
Thanks again!
