### PR TITLE
fix print-config minimal option

### LINKED ISSUE #2758: --print-config minimal doesn't work as advertised
What I tried:
(1) `rustfmt --print-config minimal .rustfmt.toml`
(2) `rustfmt --print-config minimal .rustfmt.toml src/lib.rs`

What I expected:
Invocation (1) should have produced a minimal configuration in `.rustfmt.toml` based on settings from the current directory, without formatting anything.
Invocation (2) should have done something similar, but only incorporating `src/lib.rs`.

What actually happened:
The PATH following `--print-config minimal` is both the path to the minimal config and the file to run `rustfmt` on. So, the first complains the file doesn't exist; if it exists, it tries to format it and throws a syntax error. The second is the exact same, with an extra ignored argument.

Looking at the code, I think this feature is implemented, but the command line isn't parsed correctly; `--print-config minimal` needs to consume an additional argument which is just the path to the new config. If it were parsed correctly, the behavior would be surprising, since it would both format the code and print a config (when I would expect `--print-config` to not modify the source code).

Also, note that there are no tests for either `--print-config default` or `--print-config minimal`.

### PR DESCRIPTION
**Pull request by scampi**
Close #2758

### CODE REVIEW

File: src/bin/main.rs [hunk 1]
```diff
@@ -42,6 +42,7 @@ fn main() {
 
 /// Rustfmt operations.
 enum Operation {
+    Failure(String),
```
Comment (topecongiro) [inline src/bin/main.rs]: I think that adding this variant to `Operation` is fine since it creates a minimal diff. On the other hand, I also feel that this should be part of some kind of error type.

AFAICT the return type of `determine_operation` does not need to be `ErrorKind` (it just relies on the fact that `ErrorKind` implements `From<std::io::Error>`), so what about adding a new error type that represents the failure of `determine_operation`? I am thinking of something like the following enum:

```rust
// +1 if this derives `Fail`.
enum OperationError {
    UnknownHelpTopic(String),
    UnknownPrintConfigTopic(String),
    MinimalPathWithStdin,
}
```

Please feel free to bikeshed on the naming.

File: tests/rustfmt/main.rs [hunk 2]
```diff
@@ -0,0 +1,77 @@
+//! Integration tests for rustfmt.
```
Comment (topecongiro) [inline tests/rustfmt/main.rs]: Awesome :+1:

File: src/bin/main.rs (hunk 1 above)
Comment (scampi) [reply src/bin/main.rs]: sounds good!

**Comment by scampi** [comment]
@topecongiro please have a look again, thanks!

**Comment by topecongiro** [comment]
LGTM, thank you for the update!
