### PR TITLE
fix: reject leading `.`, `)` without prefix as item marker

### LINKED ISSUE #5835: `wrap_comments` removes spaces after leading dot
Is this expected? 
```diff
❯ cargo fmt --check
Diff in /private/tmp/tmp/src/main.rs at line 1:
 fn main() {
     // f   3    .
     // t   3    .
-    // .   .    3.5
-    // .   .    -4.3
-    // .   .    .
+    // . .    3.5
+    // . .    -4.3
+    // . .    .
 }
```

```
rustfmt 1.6.0-nightly (0e8e857b 2023-07-16)
```

### PR DESCRIPTION
**Pull request by xxchan**
fix #5835

### CODE REVIEW

**Comment by xxchan** [comment]
cc @anforowicz to also take a look

**Review by anforowicz — APPROVED** [review]

**Comment by xxchan** [comment]
@ytmimi Could you take a look? Since the bug and fix are both very straightforward, and it's newly introduced.

**Comment by ytmimi** [comment]
@xxchan I'm traveling over the next few days, but I should have some time to review this early next week.

File: src/comment.rs [hunk 1]
```diff
@@ -484,7 +484,9 @@ impl ItemizedBlock {
         // allowed.
         for suffix in [". ", ") "] {
             if let Some((prefix, _)) = trimmed.split_once(suffix) {
-                if prefix.len() <= 2 && prefix.chars().all(|c| char::is_ascii_digit(&c)) {
+                if (1..=2).contains(&prefix.len())
```
Comment (ytmimi) [inline src/comment.rs:487]: Oh I see. If the `prefix.len() == 0` the condition would still pass. Good catch. I'm wondering if there's a more obvious way to write this since it took me a few seconds to figure out what `(1..=2).contains(..)` was doing.

Maybe assigning the condition to a meaningful variable name would help.

```rust
let has_leading_digits = (1..=2).contains(&prefix.len()) && prefix.chars().all(|c| char::is_ascii_digit(&c));
```

**Review by ytmimi — APPROVED** [review]
@xxchan thanks for making the edit!

To further prevent this regression it would be great to add the example from https://github.com/rust-lang/rustfmt/issues/5835#issue-1807390502 as a test case in `tests/target/`.

Happy to merge this after we add that test case and rebase on the latest master 😁

**Comment by calebcartwright** [comment]
I haven't had a chance to look at this, but before merging, can we confirm this won't introduce a formatting diff (i.e. that this won't try to modify the output/result of a prior rustfmt run)?

**Comment by xxchan** [comment]
> can we confirm this won't introduce a formatting diff (i.e. that this won't try to modify the output/result of a prior rustfmt run)?

Yes, because it makes a condition triggering the fmt change more restrictive.

**Comment by ytmimi** [comment]
@calebcartwright I ran the [diff check job before the rebase and it failed ❌](https://github.com/rust-lang/rustfmt/actions/runs/5975996729/job/16213012305) for the same reason I explained in https://github.com/rust-lang/rustfmt/pull/5853#issuecomment-1693609938.

I'm running [the job again](https://github.com/rust-lang/rustfmt/actions/runs/5978151117) now that the branch has been rebased. I'm assuming we should be good now 🤞🏼, but I'll follow up once the job completes.

**Comment by ytmimi** [comment]
@xxchan the issue mentions that `wrap_comments=true` needs to be set in order to trigger the bug. Can you update your test cases with `// rustfmt-wrap_comments: true`, and could you also add a test case using a doc comment.

**Comment by ytmimi** [comment]
@xxchan thanks again for your help on this one!
