### PR TITLE
Fix failure with `=>` in comment after match `=>`

### LINKED ISSUE #5998: rustfmt stops working if the comment just after the => of a "match" contains "=>"
Hello,

I've noticed that rustfmt stops working if the comment just after the => of a "match" contains "=>".

info :
rustfmt 1.7.0-stable (82e1608 2023-12-21)
rustc 1.75.0 (82e1608df 2023-12-21)

here's an example code :
```rust
fn main() {
    let a = 50u32;
    match a {
        10 =>
        // comment => 10
                {
            println!("A")
        }
        20 => {
                            println!("B")
        }
        _ => {
            println!("C")
        }
    }
}
```

the problem is in the comment :
`// comment => 10`

the comment contains the symbol "=>", if you try to use rustfmt it won't work.
but if you delete the "=>" from the comment, or simply add a space like this "= >", rustmt works again.

you can test the bug here :  ( click on the top-right "Tools -> Rustfmt" button to start formatting, but it won't work as long as the comment contains "=>" )
[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=41d70dfff0c31abd78d5cbe156481439)

Thank you for the wonderful work that you do :+1:

### PR DESCRIPTION
**Pull request by ding-young**
Fixes #5998 

## Background
(1) Comment without arrow `=>`
```rust
fn main() {
    match a {
        _ =>
        // comment with ==
                {
            println!("A")
        }
    }
}
```
(2) Comment without arrow `=>`
```rust
fn main() {
    match a {
        _ =>
        // comment with =>
                {
            println!("A")
        }
    }
}
```
Previously, second example fails to reformat unlike the first example. The cause was rustfmt returns original code snippet when comment is lost after rewrite. When `rewrite_match_body`, there's logic to check if comment exists between `=>` and match body, but it tries to find another `=>` in arrow_snippet considering the case with nested match. Since `=>` in comment was also caught with `rfind()`, the comment was lost, which led to silent failure. 

## Solution
Add extra check whether found `=>` was included in single line comment.

## TODO
- [ ] add more test case and verify
- [ ] think for any other alternative approach

### CODE REVIEW

File: src/matches.rs [hunk 1]
```diff
@@ -402,7 +402,16 @@ fn rewrite_match_body(
...
+        let mut arrow_index = arrow_snippet.rfind("=>").unwrap();
+        // check whether `=>` is included in the comment
+        if arrow_index != 0 {
+            let prev_arrow = arrow_snippet[..arrow_index].trim();
+            let single_line_comment_index = prev_arrow.rfind("//").unwrap_or(0);
+            let new_line_index = prev_arrow.rfind("\n").unwrap_or(0);
+            if single_line_comment_index > new_line_index {
+                arrow_index = 0;
+            }
+        }
```
Comment (ytmimi) [inline src/matches.rs:414]: rustfmt has its own `FindUncommented` trait, which is implemented for `str`. Maybe you could consider simplifying this by using the `find_last_uncommented` method.

https://github.com/rust-lang/rustfmt/blob/73c81495cdb03d1fb73dd4313466c146ca8f4d98/src/comment.rs#L1122-L1163

Comment (ding-young) [reply src/matches.rs]: Fixed it, thanks!

File: tests/source/arrow_in_comments/arrow_in_single_comment.rs [hunk 2]
```diff
@@ -0,0 +1,10 @@
+// rustfmt-wrap_comments: true
```
Comment (ytmimi) [inline tests/source/arrow_in_comments/arrow_in_single_comment.rs:1]: Just wondering, is `wrap_comments=true` needed to trigger the issue? I would expect the fix to work without needing to configure `wrap_comments`, but if it's necessary can you try to explain why?

File: src/matches.rs [hunk 3]
```diff
@@ -402,7 +402,7 @@ fn rewrite_match_body(
         let arrow_snippet = context.snippet(arrow_span).trim();
         // search for the arrow starting from the end of the snippet since there may be a match
         // expression within the guard
-        let arrow_index = arrow_snippet.rfind("=>").unwrap();
+        let arrow_index = arrow_snippet.find_last_uncommented("=>").unwrap();
```
Comment (ytmimi) [inline src/matches.rs:405]: I've been thinking a little about this and I think we should also add a [version gate](https://github.com/rust-lang/rustfmt/blob/master/Contributing.md#version-gate-formatting-changes) for this fix. If `version::One` is set we'll go with the old `arrow_snippet.rfind("=>")` code, otherwise we'll use the updated, and more accurate `arrow_snippet.find_last_uncommented("=>")`

File: tests/source/arrow_in_comments/arrow_in_single_comment.rs (hunk 2 above)
Comment (ding-young) [reply tests/source/arrow_in_comments/arrow_in_single_comment.rs:1]: It has nothing to do with `wrap_comments` option. Mistakenly left after playing around some configs. :sweat_smile:

**Review by ytmimi — APPROVED** [review]
Just reviewed this again, and everything works well! Thanks again for taking the time to work on this one. Cheers on your first contribution to rustfmt 🎉
