### PR TITLE
Fixed comment dropped between & and type issue

### LINKED ISSUE #4245: Comment dropped between & and typename in parameter type
```
pub fn a(_: &/*'static*/()) {}
```

becomes

```
pub fn a(_: &()) {}
```

any reason why this (kind of critical) bug hasn't been fixed yet? It's almost open for a year now.

_Originally posted by @hellow554 in https://github.com/rust-lang/rustfmt/issues/2781#issuecomment-496403822_

### PR DESCRIPTION
**Pull request by whizsid**
Fixes #4245 .

### CODE REVIEW

**Comment by calebcartwright** [comment]
Thank you for the PR @whizsid and apologies for the delay in review. The end result of the formatting changes look pretty good from the test cases, though I do have a few general thoughts for you on the implementation changes in types.rs

- Bit of a nit but I think using `reference` or `ref_` for local names would be more logical than using "and" naming since we aren't dealing with a logical/bitwise operator in this context
- Be sure to avoid duplicative span derivations (e.g. there's two lines that currently derive the same span from the ref token through the end of the type)
- We should be able to leverage the associated `Mutability` variant (`mt.mutbl`) to check whether or not the reference is mutable instead of needing multiple lines that scan the associated span snippets for `mut`. I think this could be shifted up front to provide a reusable bool (e.g. `is_mut`)
- Don't hesitate to leverage closures and/or add new functions to both encapsulate some common steps and to simplify things and improve readability. With the current proposed changes, the body for this match arm has nearly tripled in length, but those additions are almost exclusively within the same original match on the lifetime. My preference would be to refactor this a bit to try to minimize the nesting and extra work being done within (for example `let last_span = match *lifetime { ...` is going a whole lot more than determining the value of `last_span`).

This PR is a great start, and I'm hoping we can get your fixes tweaked/restructured a bit to achieve that goal more cleanly and with less duplication.

**Comment by whizsid** [comment]
@calebcartwright  Thank you for the review. I changed my PR to meet your suggestions.

>We should be able to leverage the associated Mutability variant (mt.mutbl) to check whether or not the reference is mutable instead of needing multiple lines that scan the associated span snippets for mut. I think this could be shifted up front to provide a reusable bool (e.g. is_mut)

Sorry I didn't used it to get only the mutable status. Currently `rustc-ap-rustc_ast` crate is not providing the `Span` of the `Mutability`. So I am calculating the `mut_lo` and `mut_hi` by getting the index of `mut` keyword. A contributor of `rust-lang` invited me to discuss this on zulip (https://github.com/rust-lang/rust/issues/78315). But I couldn't discuss it yet.

Github actions are failing because of an issue of the `rustc-ap-rustc_data_structures` crate.

**Comment by calebcartwright** [comment]
Thank you for the updates @whizsid, could you rebase to grab the latest changes off master to make CI happy?

**Comment by whizsid** [comment]
@calebcartwright CI Failed again because of a network error.

File: src/formatting/types.rs [hunk 1]
```diff
@@ -653,37 +653,74 @@ impl Rewrite for ast::Ty {
...
-                            "&{}{}",
+                    result.push_str(" ");
+                    cmnt_lo = lifetime.ident.span.hi();
+                }
+
+                let after_lt_span = mk_sp(cmnt_lo, mt.ty.span.lo());
+                let snip = context.snippet(after_lt_span);
+                if let Some(mut_pos) = snip.find_uncommented("mut") {
+                    let mut_lo = cmnt_lo + BytePos::from_usize(mut_pos);
+                    let before_mut_span = mk_sp(cmnt_lo, mut_lo);
```
Comment (calebcartwright) [inline src/formatting/types.rs:688]: We can tell directly from the AST info whether there is a `mut` present, so we should leverage that for the check to avoid doing any extra work in cases when it's not mutable. That should also let us remove a few steps here, which can also be reused to advance `cmnt_lo` down below  
```suggestion
                if ast::Mutability::Mut == mt.mutbl {
                    let mut_hi = context.snippet_provider.span_after(self.span(), "mut");
                    let before_mut_span = mk_sp(cmnt_lo, mut_hi - BytePos::from_usize(3));
```

File: src/formatting/types.rs [hunk 2]
```diff
@@ -653,37 +653,74 @@ impl Rewrite for ast::Ty {
...
-                        )
+                            before_mut_span,
+                            shape,
+                            true,
+                        )?;
+                    } else {
+                        result.push_str(mut_str);
                     }
-                })
+                    cmnt_lo = cmnt_lo + BytePos::from_usize(mut_pos + 3);
```
Comment (calebcartwright) [inline src/formatting/types.rs:701]:
```suggestion
                    cmnt_lo = mut_hi;
```

**Comment by calebcartwright** [comment]
Thanks for the update @whizsid! I find this to be easier to read :+1:

One minor item left inline to leverage `ast::Mutability` to avoid doing unnecessary work, but otherwise LGTM

**Comment by calebcartwright** [comment]
Excellent, thank you for the PR and all the good work you've been doing lately @whizsid!
