### PR TITLE
Fix cargo fmt inconsistency

### LINKED ISSUE #3461: Cargo fmt --all -- --check does not check every file in workspace with multiple editions
`Cargo fmt --all -- --check` executes `rustfmt` twice: `rustfmt --edition 2015 [files]` and `rustfmt --edition 2018 [files]`. When the former fails, the latter won't get executed.

### PR DESCRIPTION
**Pull request by topecongiro**
- Make sure that we run rustfmt against every edition
- Use BTreeMap to guarantee consistent ordering

Closes #3461.

### CODE REVIEW

File: src/cargo-fmt/main.rs [hunk 1]
```diff
@@ -357,13 +366,14 @@ fn run_rustfmt(
...
 
-        let status = command.wait()?;
-        if !status.success() {
-            return Ok(status.code().unwrap_or(FAILURE));
-        }
+        status.push(command.wait()?);
     }
 
-    Ok(SUCCESS)
+    Ok(status
```
Comment (scampi) [inline src/cargo-fmt/main.rs]: Nice
