### PR TITLE
Fix issues with formatting imports with comments

### LINKED ISSUE #5852: Comments in imports are formatted incorrectly
Examples:
```rs
use std::{
    fs,
    // (temporarily commented, we'll need this again in a second) io,
};

use foo::{
    self // this is important
};
```

Becomes:
```rs
use std::fs;

use foo::{self, // this is important};
```

Which now has syntax errors.

### PR DESCRIPTION
**Pull request by rsammelson**
Fixes #5852

### CODE REVIEW

File: src/imports.rs [hunk 1]
```diff
@@ -1032,7 +1032,9 @@ fn rewrite_nested_use_tree(
 
     let list_str = write_list(&list_items, &fmt)?;
 
-    let result = if (list_str.contains('\n') || list_str.len() > remaining_width)
+    let result = if (list_str.contains('\n')
+        || list_str.len() > remaining_width
+        || tactic == DefinitiveListTactic::Vertical)
```
Comment (ytmimi) [inline src/imports.rs:1037]: When you get a chance can you explain why we need to add the `tactic == DefinitiveListTactic::Vertical)` check.

File: tests/source/use.rs [hunk 2]
```diff
@@ -0,0 +1,95 @@
+use foo :: bar
+;
+
```
Comment (ytmimi) [inline tests/source/use.rs:3]: Can you rename `tests/[source/target]/use.rs` to `tests/[source/target]/issue_5852.rs` so we can associate these test cases with that issue. Also, can you include the code snippets from the issue as test cases too.

File: src/imports.rs (hunk 1 above)
Comment (rsammelson) [reply src/imports.rs:1037]: This is to resolve the second problem shown in the issue. The problem is that it will try to put in on one line because the list doesn't contain a newline (because there is only one actual item, and the newlines are only between items).

File: tests/source/use.rs (hunk 2 above)
Comment (rsammelson) [reply tests/source/use.rs]: The code snippets are semantically equivalent to the third and sixth cases in the test file.

Comment (ytmimi) [reply tests/source/use.rs]: It never hurts to have more tests 😁. I'd appreciate it if you could add those code snippets.

Comment (rsammelson) [reply tests/source/use.rs]: @ytmimi done

File: src/imports.rs (hunk 1 above)
Comment (ytmimi) [reply src/imports.rs:1037]: Got it. It looks like `tactic` is somewhat influenced by the user's specified value for `imports_layout`. Out of an abundance of caution can you make sure that this fix holds for all values of `imports_layout`. Probably best to create a `issue-5852` directory and add a test case for each `imports_layout` variant.

Comment (rsammelson) [reply src/imports.rs:1037]: @ytmimi sorry for the delayed response, but it should be fixed now

**Comment by ytmimi** [comment]
@rsammelson when you have a moment can you quickly verify that this PR addresses #5877. I'm almost positive that it does I just want to get confirmation.

**Comment by rsammelson** [comment]
Yes, that is what this fixes.

**Comment by ytmimi** [comment]
> Yes, that is what this fixes.

Thank you for the quick reply!

**Comment by rsammelson** [comment]
What is the status on this being merged?

**Comment by calebcartwright** [comment]
> What is the status on this being merged?

Somewhat vague answer though it's a somewhat vague question, but essentially we'll get to it when we can. The code diff looks small and the tests look thorough which is a great sign (and thank you for all the tests!).

I've kicked off one of our automated jobs that does more thorough levels of idempotence testing to try to give us a greater degree of confidence the proposed changes won't introduce any unexpected/unintentional formatting side effects, let's see how that goes -> https://github.com/rust-lang/rustfmt/actions/runs/5849405920

**Comment by rsammelson** [comment]
It looks like there might be a problem, so I'll take a look at it.

**Comment by ytmimi** [comment]
@rsammelson rebasing on the latest master should resolve the issue in the diff check job.

The diff I'm seeing occurring because your branch doesn't include the fix for #5882

```diff
-macro_rules! foo {}
+macro_rules! foo {
+    
+}
```

**Comment by ytmimi** [comment]
Thanks for rebasing. [Let's give the job another run](https://github.com/rust-lang/rustfmt/actions/runs/5978914387).

**Comment by ytmimi** [comment]
@rsammelson I believe we could close https://github.com/rust-lang/rustfmt/pull/5290 if we get this merged. When you have a moment, can you double check that this also resolves https://github.com/rust-lang/rustfmt/issues/4708.

I have a feeling that this doesn't quite resolve https://github.com/rust-lang/rustfmt/issues/3984, specifically this input might still be buggy:

```rust
use a::{item /* comment */};
use b::{
    a,
    // comment
    item,
};
use c::item /* comment */;
use d::item; // really long comment (with `use` exactly 100 characters) ____________________________

use std::e::{/* it's a comment! */ bar /* and another */};
use std::f::{/* it's a comment! */ bar};
use std::g::{bar /* and another */};
```

I'm not suggesting you need to solve this one here, but I do want to make a note of it.

**Comment by rsammelson** [comment]
Yes, that issue looks the same as one of the test cases I have, so it should be fixed.

**Comment by rsammelson** [comment]
> ```rust
> use a::{item /* comment */};
> use b::{
>     a,
>     // comment
>     item,
> };
> use c::item /* comment */; // THIS LINE
> use d::item; // really long comment (with `use` exactly 100 characters) ____________________________
> 
> use std::e::{/* it's a comment! */ bar /* and another */};
> use std::f::{/* it's a comment! */ bar};
> use std::g::{bar /* and another */};
> ```

@ytmimi Actually, it looks like the only thing broken in that block is the marked line, which is fixed? (I'm not sure how changes are incorporated here, since the fix isn't in master) in #4759. I added a test with the other lines.

**Comment by ytmimi** [comment]
> @ytmimi Actually, it looks like the only thing broken in that block is the marked line, which is fixed? (I'm not sure how changes are incorporated here, since the fix isn't in master) in https://github.com/rust-lang/rustfmt/pull/4759. I added a test with the other lines.

@rsammelson thanks for looking into this! https://github.com/rust-lang/rustfmt/pull/4759 is a great find! The PR is marked as [backport-triage](https://github.com/rust-lang/rustfmt/issues?q=label%3Abackport-triage+is%3Aclosed), which means that the fix isn't currently available on the trunk branch. If you run `git branch -a --contains e10d2d7` you'll see that the commit is available on the `rustfmt-2.0.0-rc.2` branch.

I don't mean to keep expanding the scope of this PR, but would you mind investigating whether applying similar changes would resolve the issue?

File: tests/target/issue-5852/new.rs
Comment (ytmimi) [inline tests/target/issue-5852/new.rs:1]: These test cases came from https://github.com/rust-lang/rustfmt/issues/3984. Please pull this test file out of the `issue-5852` folder and name it something like `issue_3984.rs` so we can better link these test cases to the original issue.

However, it might be better to exclude these test cases until we've backported https://github.com/rust-lang/rustfmt/pull/4759,

**Comment by rsammelson** [comment]
Alright, I will try to backport that fix and move the tests; if I can't backport it I'll just get rid of the test for now.

**Comment by rsammelson** [comment]
I was able to pull in the commit, and it fixes the problem from the test block you mentioned, but the test cases added in the fix commit are still broken so the backport is not completely successful. I think it's sufficient for this PR though.

**Comment by ytmimi** [comment]
> I was able to pull in the commit, and it fixes the problem from the test block you mentioned, but the test cases added in the fix commit are still broken so the backport is not completely successful. I think it's sufficient for this PR though.

Just to be clear, what you're saying is that more work is needed to fully backport https://github.com/rust-lang/rustfmt/pull/4759?

Could you highlight which test cases are still broken?

**Comment by rsammelson** [comment]
Yes, all test files added in that PR are broken (mostly incorrect indentation), but applying (at least part of) the fix doesn't break anything that wasn't already broken. It fixed the problem with `use thing /* comment */;`.

**Comment by ytmimi** [comment]
> Yes, all test files added in that PR are broken (mostly incorrect indentation), but applying (at least part of) the fix doesn't break anything that wasn't already broken. It fixed the problem with use thing `/* comment */;`.

If I remember correctly that's because those multi-line comment fixes are predicated on a different backport, but I agree that those changes aren't necessary to solve the current issue.

I think we're good to go here. My last ask is to squash your first two commits into one and rebase on the latest master. I think we should keep the backport commit and test cases for https://github.com/rust-lang/rustfmt/issues/3984, separate.

**Comment by rsammelson** [comment]
Alright it should be good now.

**Comment by ytmimi** [comment]
@rsammelson the backport commit technically needs to come before the Improve tests commit since the tests for https://github.com/rust-lang/rustfmt/issues/3984, will fail if the backport isn't applied.  Can you adjust the order of the commits.

**Comment by rsammelson** [comment]
Good point, I didn't think about that. It's fixed.

**Review by ytmimi — APPROVED** [review]
I appreciate you sticking with this through all the revisions I've asked for.

I ran [this diff check job before the commits were reordered](https://github.com/rust-lang/rustfmt/actions/runs/6031747073/job/16365903640) and [I ran this diff check job after the commits were reordered](https://github.com/rust-lang/rustfmt/actions/runs/6032714793/job/16368304176) (just being overly cautious), and both passed so I'm feeling very good about this!

Oh, and thanks for your first contribution to rustfmt 🎉

**Comment by rsammelson** [comment]
Thanks!
