### PR TITLE
Fix duplicate import removal for imports_granularity="Module"

### LINKED ISSUE #6243: strange behavior for duplicate imports with imports_granularity="Module"
e.g.,

```rust
use risingwave_batch::executor::{BoxedExecutor, JoinType};
use risingwave_batch::executor::{BoxedExecutor, JoinType};
```

After first fmt
```rust
use risingwave_batch::executor::{BoxedExecutor, BoxedExecutor, JoinType, JoinType};
```

After second fmt
```rust
use risingwave_batch::executor::{BoxedExecutor, JoinType, JoinType};
```

The behavior I want is that it can remove duplicates, like ` imports_granularity="Crate"`

### PR DESCRIPTION
**Pull request by tqwewe**
Fixes #6243 - Strange behavior for duplicate imports with imports_granularity="Module"

## Problem
When using `imports_granularity="Module"`, duplicate imports were being merged but not deduplicated, requiring multiple formatting passes to reach a stable state. This was inconsistent with other granularity settings which properly remove duplicates.

## Solution
Added `.dedup()` calls after sorting import lists in three locations:
- `merge_rest()` - when creating merged import lists
- `UseTree::normalize()` - when normalizing nested imports
- `merge_use_trees_inner()` - when merging use trees

This ensures duplicate imports are removed in a single formatting pass, matching the behavior of `Crate` and `Item` granularity settings.

## Test Changes
Updated `tests/target/multiple.rs` to expect deduplicated imports. I believe the previous test was documenting the buggy behavior rather than the expected behavior.

## Example
Before (unstable, requires 2 passes):
```rust
use risingwave_batch::executor::{BoxedExecutor, JoinType};
use risingwave_batch::executor::{BoxedExecutor, JoinType};
// First pass: {BoxedExecutor, BoxedExecutor, JoinType, JoinType}
// Second pass: {BoxedExecutor, JoinType}
```

After (stable, single pass):
```rust
use risingwave_batch::executor::{BoxedExecutor, JoinType};
```

### CODE REVIEW

File: tests/target/multiple.rs [hunk 1]
```diff
@@ -16,11 +16,7 @@ extern crate foo;
 extern crate foo;
 
 use std::cell::*;
-use std::{
```
Comment (Manishearth) [inline tests/target/multiple.rs:19]: Hmm. Should we have this test at all? This original code won't compile, and now the use tree is much smaller. We should tweak this to import a lot of items

cc @calebcartwright if you have an idea as to what this test was doing before

File: tests/target/multiple.rs [hunk 2]
```diff
@@ -16,11 +16,7 @@ extern crate foo;
...
-    self, any, ascii, borrow, borrow, borrow, borrow, borrow, borrow, borrow, borrow, borrow,
-    borrow, borrow, boxed, boxed, boxed, boxed, boxed, boxed, boxed, boxed, boxed, boxed, char,
-    char, char, char, char, char, char, char, char, char,
-};
+use std::{self, any, ascii, borrow, boxed, char};
```
Comment (Manishearth) [inline tests/target/multiple.rs:19]: Wait, this is changing behavior without this flag.

However, this code is _broken_, so perhaps that's fine?

File: tests/target/multiple.rs (hunk 1 above)
Comment (Manishearth) [reply tests/target/multiple.rs:19]: I still think this should be fixed: let's change this to a test that imports a lot of different items.

Comment (calebcartwright) [reply tests/target/multiple.rs:19]: rustfmt does still have to work on code that doesn't compile, provided it can still be parsed.

I'm not sure what the thinking was for making that distinction back in the day, but it made sense to me in the context of an inner dev-loop and format on save in editors

Comment (Manishearth) [reply tests/target/multiple.rs:19]: Yeah, makes sense. We shouldn't have any stability around that but we should test it I guess.
