### PR TITLE
Format trait aliases with where clauses

### LINKED ISSUE #3584: rustfmt strips the `where` clause from trait alias
Input:

```rust
#![feature(trait_alias)]
trait A = where for<'b> &'b Self: Send;
```

Unexpected rustfmt output:

```rust
#![feature(trait_alias)]
trait A = ;
```

* rustfmt version: `1.2.2-nightly (2019-04-24 5274b49)`

### PR DESCRIPTION
**Pull request by topecongiro**
Closes #3584.

### CODE REVIEW

File: src/items.rs [hunk 1]
```diff
@@ -1156,6 +1154,45 @@ pub(crate) fn format_trait(
...
+            Density::Compressed,
+            ";",
+            None,
+            self.generics.where_clause.span.lo(),
+            option,
+        )?;
+
+        let fits_single_line = !generic_bounds_str.contains('\n')
+            && !where_str.contains('\n')
+            && generic_bounds_str.len() + where_str.len() + 1 <= shape.width;
```
Comment (scampi) [inline src/items.rs]: should this use `utils::unicode_str_width` instead of `len` in order to take into account some unicode character ? One may occur in a comment inside, e.g., `where_str`.

File: src/items.rs [hunk 2]
```diff
@@ -2467,25 +2535,104 @@ fn rewrite_where_clause_rfc_style(
...
         rewrite_comments_before_after_where(context, span_before, span_after, shape)?;
 
-    let starting_newline = if where_clause_option.snuggle && comment_before.is_empty() {
-        Cow::from(" ")
-    } else {
-        block_shape.indent.to_string_with_newline(context.config)
+    let starting_newline = match where_clause_option.snuggle {
+        WhereClauseSpace::Space if comment_before.is_empty() => Cow::from(" "),
+        WhereClauseSpace::None => Cow::from(""),
+        _ => block_shape.indent.to_string_with_newline(context.config),
```
Comment (scampi) [inline src/items.rs]: I think it'd be nicer to be explicit here:

```suggestion
        WhereClauseSpace::Newline => block_shape.indent.to_string_with_newline(context.config),
```

Comment (topecongiro) [reply src/items.rs]: I agree that writing a pattern explicitly makes it more readable. In this particular pattern, however, we cannot rewrite in the suggested way because of the guard. We could replace `_` with  `WhereClauseSpace::Newline | WhereClauseSpace::Space`, though in this case, I prefer the original.
