### PR TITLE
fix panic on closure with empty block expr

### LINKED ISSUE #3844: panic on valid expression: `|| {{}}`
The following valid input induces a panic:

```rust
fn main() {
    || {{}};
}
```

```bash
echo 'fn main() { || {{}}; }' | rustfmt
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libcore/slice/mod.rs:2715:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

Version:

```
rustfmt 1.4.4-stable (0462008d 2019-08-06)
```

### PR DESCRIPTION
**Pull request by calebcartwright**
Fixes #3844

### CODE REVIEW

File: src/closures.rs [hunk 1]
```diff
@@ -91,9 +91,12 @@ fn get_inner_expr<'a>(
 ) -> &'a ast::Expr {
     if let ast::ExprKind::Block(ref block, _) = expr.kind {
         if !needs_block(block, prefix, context) {
-            // block.stmts.len() == 1
-            if let Some(expr) = stmt_expr(&block.stmts[0]) {
-                return get_inner_expr(expr, prefix, context);
+            // block.stmts.len() == 1 except with `|| {{}}`;
+            // https://github.com/rust-lang/rustfmt/issues/3844
+            if !block.stmts.is_empty() {
+                if let Some(expr) = stmt_expr(&block.stmts[0]) {
```
Comment (topecongiro) [inline src/closures.rs]: Nit: recently I prefer to use `.first().map()` in a case like this to avoid array indexing as much as possible:

```rust
                if let Some(expr) = block.stmts.first().map(stmt_expr) {
```

Comment (calebcartwright) [reply src/closures.rs]: Makes sense, I'll update that

Comment (topecongiro) [reply src/closures.rs]: Multi-line comments, very nice :raised_hands:

Comment (calebcartwright) [reply src/closures.rs]: Lol, I was just admiring that myself. I'm hoping to see review inline suggestions for multiline blocks soon 🤞

File: src/closures.rs [hunk 2]
```diff
@@ -91,8 +91,9 @@ fn get_inner_expr<'a>(
 ) -> &'a ast::Expr {
     if let ast::ExprKind::Block(ref block, _) = expr.kind {
         if !needs_block(block, prefix, context) {
-            // block.stmts.len() == 1
-            if let Some(expr) = stmt_expr(&block.stmts[0]) {
+            // block.stmts.len() == 1 except with `|| {{}}`;
+            // https://github.com/rust-lang/rustfmt/issues/3844
+            if let Some(Some(expr)) = block.stmts.first().map(stmt_expr) {
```
Comment (topecongiro) [inline src/closures.rs]: My bad...we should use `and_then` instead of `map` in this case.
```suggestion
            if let Some(expr) = block.stmts.first().and_then(stmt_expr) {
```

Comment (calebcartwright) [reply src/closures.rs]: No worries!

**Comment by topecongiro** [comment]
Sorry for the multiple requests. Looks good to merge!
