### PR TITLE
Fix/comments inside trait generics gets duplicated

### LINKED ISSUE #5358: /* comment */ inside trait generics gets duplicated
```rust
trait Test</* comment */ T> {}
```

Gets reformatted as

```rust
trait Test</* comment */ T> /* comment */ T> {}
```

Whereas no changes were expected.

Playground:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=88c36ba8a83e2c01030bbbf95327be6a

Setting `version = Two` has no effect.

```
λ rustfmt --version
rustfmt 1.4.38-stable (7737e0b 2022-04-04)
```

### PR DESCRIPTION
**Pull request by jmj0502**
# Fixes #5358 
* Now the value of `comment_hi` is equals to the `generic.span.lo` if there actually are any generic parameters, otherwise it will kept the value previously defined.

### CODE REVIEW

File: tests/target/issue-5358.rs [hunk 1]
```diff
@@ -0,0 +1,4 @@
+// Test /* comment */ inside trait generics gets duplicated.
```
Comment (ytmimi) [inline tests/target/issue-5358.rs:1]: Should this read `Test /* comment */ inside trait generics does not get duplicated`?

Comment (jmj0502) [reply tests/target/issue-5358.rs:1]: Yes! I'll fix it un a few minutes.

Comment (jmj0502) [reply tests/target/issue-5358.rs]: Done!

**Review by ytmimi — APPROVED** [review]
Thanks for your first contribution 🎉
