### PR TITLE
Handle a macro argument with a single keyword

### LINKED ISSUE #3331: Regression in formatting Syn's token macro
Our CI hit a surprising formatting change: https://travis-ci.org/dtolnay/syn/jobs/490139618.

```diff
 #[cfg(any(feature = "full", feature = "derive"))]
 pub fn fold_abi<V: Fold + ?Sized>(_visitor: &mut V, _i: Abi) -> Abi {
     Abi {
-        extern_token: Token![extern](tokens_helper(_visitor, &_i.extern_token.span)),
+        extern_token: Token ! [ extern ](tokens_helper(_visitor, &_i.extern_token.span)),
         name: (_i.name).map(|it| _visitor.fold_lit_str(it)),
     }
 }
```

I minimized this to:

```bash
echo 'Token ! [ extern ];' | cargo run --bin rustfmt
```

Before f4f9502e:

```rust
Token![extern];
```

Since f4f9502e:

```rust
Token ! [ extern ];
```

Mentioning @topecongiro and @scampi who were involved in that PR.

### PR DESCRIPTION
**Pull request by topecongiro**
Closes #3331.

### CODE REVIEW

File: src/macros.rs [hunk 1]
```diff
@@ -224,6 +226,24 @@ pub fn rewrite_macro(
     result
 }
 
+fn check_keyword<'a, 'b: 'a>(parser: &'a mut Parser<'b>) -> Option<MacroArg> {
+    for &keyword in RUST_KEYWORDS.iter() {
+        if parser.token.is_keyword(keyword)
+            && parser.look_ahead(1, |t| {
+                debug!("{:?}", t);
```
Comment (scampi) [inline src/macros.rs]: I think this debug statement can be removed

**Comment by dtolnay** [comment]
Thanks! Could this be applied more generally for any single token, even if that token is not a keyword or expression? For example:

```rust
let _ = Token![::];
let _ = Token![""s];
```

**Comment by topecongiro** [comment]
@dtolnay Yes it could. Currently rustfmt just keep those kind of macro calls as is.
