### PR TITLE
Catch possible tokenizer panics

### LINKED ISSUE #3239: Parse panic doesn't seem to be caught?
This showed up as a part of RLS test failure. The string in question is
```
/// Bar variant\nBar,\n/// Baz variant\nBaz\n}\n\n/// Bar struct\npub struct Bar<T>{}
```

Repro: https://github.com/Xanewok/simple_fmt/tree/master

I'd expect the parser to catch possible panics:
https://github.com/rust-lang/rustfmt/blob/fbeabe9547954195a65077a54d41956257086ffb/src/formatting.rs#L622

however it seems to be an aborting panic? (no backtrace)

Is this completely on rustc side or can we do something here to not abort on parse error?

### PR DESCRIPTION
**Pull request by Xanewok**
When using `new_parser_from_source_str` sometimes it can panic on incomplete input (e.g. bare `}`), so here we use the `Result`-returning `maybe_new_parser_from_source_str` variant to catch possible errors and diagnostics to emit later.

Closes #3239 

related #753 
cc @topecongiro

### CODE REVIEW

File: src/formatting.rs [hunk 1]
```diff
@@ -604,30 +604,41 @@ fn parse_crate(
 ) -> Result<ast::Crate, ErrorKind> {
     let input_is_stdin = input.is_text();
 
-    let mut parser = match input {
-        Input::File(file) => parse::new_parser_from_file(parse_session, &file),
-        Input::Text(text) => parse::new_parser_from_source_str(
+    let parser = match input {
+        Input::File(file) => Ok(parse::new_parser_from_file(parse_session, &file)),
```
Comment (Xanewok) [inline src/formatting.rs]: Actually, the same thing can happen to the file case: https://github.com/rust-lang/rust/blob/1839c144bc6db8c07945caacd449aa7f3a76cd47/src/libsyntax/parse/mod.rs#L211.

Should I use `maybe_source_file_to_parser` here as well?

Comment (topecongiro) [reply src/formatting.rs]: > Should I use maybe_source_file_to_parser here as well?

I think ideally we should, though I think it is a low priority compared to stdin case as panicking on the file case seems fine.

Comment (Xanewok) [reply src/formatting.rs]: Okay then, I'll leave the file case as-is (and it's still blocked on https://github.com/rust-lang/rust/pull/56658).

File: src/formatting.rs [hunk 2]
```diff
@@ -73,7 +73,12 @@ fn format_project<T: FormatHandler>(
     let source_map = Rc::new(SourceMap::new(FilePathMapping::empty()));
     let mut parse_session = make_parse_sess(source_map.clone(), config);
     let mut report = FormatReport::new();
-    let krate = parse_crate(input, &parse_session, config, &mut report)?;
+    let krate = match parse_crate(input, &parse_session, config, &mut report) {
+        Ok(krate) => krate,
+        // Surface parse error via Session (errors are merged there from report)
+        Err(ErrorKind::ParseError) => return Ok(report),
```
Comment (Xanewok) [inline src/formatting.rs]: Changed this to return report here for parse errors, otherwise we eagerly `?`-return an `Err` here:
https://github.com/rust-lang/rustfmt/blob/66c98db50f58aa97be7bdd34af136ad258c6e04c/src/formatting.rs#L76
but we only add errors to `Session` if we have `Ok(FormatReport)`
https://github.com/rust-lang/rustfmt/blob/66c98db50f58aa97be7bdd34af136ad258c6e04c/src/formatting.rs#L49-L57

I changed this because I expected `session.has_parsing_errors()` call to work:
https://github.com/rust-lang/rustfmt/pull/3240/files#diff-382d140f826c9bd99f62116b9712fad3R299
and it seemed like a special case that it didn't.

However, for IO errors we still will get `Err(_)` from `Session::format(...)` and `session.has_operational_errors()` will return `false` (should we also change that?).

**Comment by Xanewok** [comment]
This should be ready to review now

**Comment by topecongiro** [comment]
Thank you!

**Comment by wada314** [comment]
Hello, 

I'm running "$ cargo test stdin_parser_panic_caught" in nightly Rust, Windows 10.
The test itself successfully finishes, but the panic!() outputs are not suppressed and displayed in my console.
Is this an expected behavior? Or is this something happening only in my environment?

thanks,

```
running 1 test
error: this file contains an un-closed delimiter
 --> <stdin>:1:2
  |
1 | {
  | -^
  | |
  | un-closed delimiter

error: expected item, found `{`
 --> <stdin>:1:1
  |
1 | {
  | ^ expected item

error: unexpected close delimiter: `}`
 --> <stdin>:1:1
  |
1 | }
  | ^ unexpected close delimiter

test test::stdin_parser_panic_caught ... ok
```
