### PR TITLE
Indent return types separated from params by newline

### LINKED ISSUE #4366: 2.0.0-rc.2 formatting regression with line-wrapped functions
**Input**

```rust
// rustfmt-max_width: 80
trait GetMetadata {
    fn metadata(loc: ApiEndpointParameterLocation)
        -> Vec<ApiEndpointParameter>;
}
```

**Output**

```rust
// rustfmt-max_width: 80
trait GetMetadata {
    fn metadata(loc: ApiEndpointParameterLocation)
    -> Vec<ApiEndpointParameter>;
}
```

**Expected output**

```rust
// rustfmt-max_width: 80
trait GetMetadata {
    fn metadata(loc: ApiEndpointParameterLocation)
        -> Vec<ApiEndpointParameter>;
}
```

**Meta**

- rustfmt version: rustfmt 2.0.0-rc.2-nightly (0921e1fb 2020-07-29)
- From where did you install rustfmt?: built from source

### PR DESCRIPTION
**Pull request by ayazhafiz**
#3891 removed Version One formatting that did this correctly (https://github.com/rust-lang/rustfmt/pull/3891/files#diff-5db152a52bdaeae9dacd35f43a4a78ddL2342-L2344),
but at seemingly at the time there were no tests to catch the
regression.

This commit fix-forwards the formatting regression, though via a different
implementation because the original implementation would muddle the branch
for visual indentation and this fix, which is probably not preferrable
giving the existing complexity of the rewrite_required_fn method.

Closes #4366

### CODE REVIEW

File: src/formatting/items.rs [hunk 1]
```diff
@@ -2405,15 +2407,13 @@ fn rewrite_fn_base(
...
+                    // Aligning with non-existent params looks silly, as does aligning the return
+                    // type when it is on a newline entirely disconnected from the parentheses of
+                    // the parameters.
                     force_new_line_for_brace = true;
-                    ret_shape = if context.use_block_indent() {
-                        ret_shape.offset_left(4).unwrap_or(ret_shape)
-                    } else {
-                        ret_shape.indent = ret_shape.indent + 4;
-                        ret_shape
-                    };
```
Comment (ayazhafiz) [inline src/formatting/items.rs:2416]: #3731 added this, but I am not sure that the branch is needed. It doesn't break any tests, and I don't understand what `offset_left` is supposed to do in this case.

Comment (calebcartwright) [reply src/formatting/items.rs:2416]: Hmm. Would you mind leaving it in then, at least for now, so that I can go ahead and merge? I really appreciate @ahl test driving the 2.0 beta and would prefer to get the bug fix merged, and we can investigate the necessity of this conditional in a follow up.

Thoughts?

Comment (ayazhafiz) [reply src/formatting/items.rs:2416]: Sounds good, I have reverted the changes.

Comment (calebcartwright) [reply src/formatting/items.rs]: Awesome, thank you!

**Comment by calebcartwright** [comment]
Thanks @ayazhafiz!
