### PR TITLE
Fixed Issue 'Trailing comma is duplicated when obstructed by comments'

### LINKED ISSUE #3876: Trailing comma is duplicated when obstructed by comments
In the following snippet, there is a trailing comment following the entire builder chain after `normal_message`:
```rust
    // Client set up {{{
    discord_client.with_framework(
        StandardFramework::new()
            // Framework configuration {{{{
            .configure(|c| {
                c.with_whitespace(true) // allow `{prefix} command`
                    .case_insensitivity(true) // allow `{prefix}cOmMaNd`
                    .no_dm_prefix(true) // allow `command` in DMs
                    .prefix(config.prefix()) // set the prefix to use for commands
                    .delimiters(vec![" "]) // split arguments at space; `{prefix} test a b c` => [{prefix test}, a, b, c]
            })
            // Normal message {{{{
            .normal_message(|_ctx, _msg| {
            })
            // }}}}
            ,
            // wee
    );
    // }}}
```

When I run `rustfmt` on this with default settings:
```console
$ rustfmt --version
rustfmt 1.4.8-nightly (afb1ee1 2019-09-08)
```

I get this result:
```rust
    // Client set up {{{
    discord_client.with_framework(
        StandardFramework::new()
            // Framework configuration {{{{
            .configure(|c| {
                c.with_whitespace(true) // allow `{prefix} command`
                    .case_insensitivity(true) // allow `{prefix}cOmMaNd`
                    .no_dm_prefix(true) // allow `command` in DMs
                    .prefix(config.prefix()) // set the prefix to use for commands
                    .delimiters(vec![" "]) // split arguments at space; `{prefix} test a b c` => [{prefix test}, a, b, c]
            })
            // Normal message {{{{
            .normal_message(|_ctx, _msg| {}), // }}}}
                                              , // uh oh.. there's a comma over this one as well! ;o
                                              // wee
    );
    // }}}
```

The comma clearly duplicated where it wasn't supposed to. 
The //uh oh comment was added in the issue creation; the rest was from my source code, except "a bit" stripped down.

### PR DESCRIPTION
**Pull request by whizsid**
Fixes #3876 .

### CODE REVIEW

File: tests/target/issue-3876.rs [hunk 1]
```diff
@@ -0,0 +1,14 @@
...
+{
+}
+
+fn main() {
+    foo(
+        x // comment 1
+          ,
+          // comment 2
+    )
+}
```
Comment (calebcartwright) [inline tests/target/issue-3876.rs:14]: This is a slight improvement in that the commas are not duplicated, though the formatting doesn't feel quite right. In particular I'm confused by the indentation/alignment in the first snippet, as well as the position of the `,` in the second.

I think a big question is whether there's a valid use case for comments _before_ the comma, or whether that's just unintentional i.e.:

```rust
fn main() {
    foo(
        x, // comment 1
        // comment 2
    )
}
```
although at the moment I suspect rustfmt may want to do this, though that's largely due to a bug in default visual alignment for comments (refs #4108)
```rust
fn main() {
    foo(
        x, // comment 1
           // comment 2
    )
}
```

**Comment by whizsid** [comment]
Sorry I was away from open source in last months. @calebcartwright Can you review again?

File: src/formatting/lists.rs [hunk 2]
```diff
@@ -734,17 +739,31 @@ pub(crate) fn extract_post_comment(
...
+                .trim_matches('\n'),
+            "\n",
+            post_snippet[sep_pos + separator.len()..]
+                .trim_matches(white_space)
+                .trim_matches('\n'),
+        ]
+        .concat()
     } else {
-        post_snippet
+        post_snippet.to_string()
```
Comment (calebcartwright) [inline src/formatting/lists.rs:766]: I'd want to avoid always allocating in each branch as it shouldn't be necessary to do so. I know the ownership rules make getting a slice out of the block where there's a `,` nested between comments but there's a few ways to work around this.

One would be to have an unused local mutable variable defined outside the big control flow expression (with an initial String::new assignment to avoid allocating unless and until needed) and then in the nested branch on line 753 that unused local can be assigned to the temp concat string, and the conditional block could then return a slice.

e.g. up above on line ~739 adding a new local (but with a better name :smile:) 
```rust
    // Cleanup post-comment: strip separators and whitespace.
    let post_snippet = post_snippet[..comment_end].trim();
    let mut _nested_comment_case_foo_bar_local = String::new();
    let post_snippet_trimmed = if post_snippet.starts_with(|c| c == ',' || c == ':') {
```

and then use that `_nested_comment_case_foo_bar_local` in this branch:

```rust
        _nested_comment_case = [
            post_snippet[..sep_pos]
                .trim_matches(white_space)
                .trim_matches('\n'),
            "\n",
            post_snippet[sep_pos + separator.len()..]
                .trim_matches(white_space)
                .trim_matches('\n'),
        ]
        .concat();

        &_nested_comment_case_foo_bar_local
```

Perhaps another approach could be to have the conditional return a tuple that would contain the array of slices and a boolean indicator as to whether the entries need to be concatenated

File: src/formatting/lists.rs [hunk 3]
```diff
@@ -734,17 +739,31 @@ pub(crate) fn extract_post_comment(
...
     // not comment or over two lines
     else if post_snippet.ends_with(',')
         && (!post_snippet.trim().starts_with("//") || post_snippet.trim().contains('\n'))
     {
-        post_snippet[..(post_snippet.len() - 1)].trim_matches(white_space)
+        post_snippet[..(post_snippet.len() - 1)]
+            .trim_matches(white_space)
+            .to_string()
+    } else if post_snippet.find_uncommented(",").is_some() {
+        let sep_pos = post_snippet.find_uncommented(",").unwrap();
```
Comment (calebcartwright) [inline src/formatting/lists.rs:754]: While I'd love to avoid having to do this full scan more than once, we can certainly avoid having to do it a third time here by using an `if let Some..` in the conditional which will also be a bit more idiomatic

```suggestion
    } else if let Some(sep_pos) = post_snippet.find_uncommented(",") {
```

File: tests/source/issue-3876.rs [hunk 4]
```diff
@@ -0,0 +1,29 @@
...
+        // comment 1
+
+
+        ,
+
+
+
+        // comment 2
+    )
+}
```
Comment (calebcartwright) [inline tests/source/issue-3876.rs:29]: Could you also add some test cases that include multi-line block style comments?

**Review by calebcartwright — COMMENTED** [review]
Thanks for this! It's in pretty good shape though think we can optimize it a bit and have also requested some additional tests

File: src/formatting/lists.rs (hunk 2 above)
Comment (whizsid) [reply src/formatting/lists.rs]: Wow! I was unaware of this tactical approach to solving ownership problems. Thanks for sharing it.  :heart:

**Comment by calebcartwright** [comment]
Excellent thank you!
