### PR TITLE
fix Erasing inner attributes in struct

### LINKED ISSUE #3592: Erasing inner attributes in blocks
```rust
#![allow(unused)]
struct Biz {
    field: usize,
}

fn r() -> (Biz, ()) {
    (
        Biz{
            #![cfg(unix)]
            field: 9,
        },
        Biz{
            #![cfg(not(unix))]
            field: 200,
        },
        ()
    )
}
fn main() {
    println!("Hello, world!");
}
```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=017f6e619b60b265f62758d606d07e99))

Running rustfmt on this code erases the #![cfgs], and creates an invalid return type. I am not sure if the tuple is necessary but I had one when I first encountered the bug.

This occurs no matter how many fields are in the struct or block.

This seems similar to #2073, but since that issue is so old and marked as solved I felt it would be better to open a new one.

rustfmt 1.2.2-nightly (5274b49 2019-04-24)

### PR DESCRIPTION
**Pull request by rchaser53**
fix #3592

### CODE REVIEW

File: src/patterns.rs [hunk 1]
```diff
@@ -226,7 +226,8 @@ fn rewrite_struct_pat(
         }
     }
 
-    let fields_str = wrap_struct_field(context, &fields_str, shape, v_shape, one_line_width);
+    // ast::Pat doesn't attrs so use &[]
```
Comment (scampi) [inline src/patterns.rs]:
```suggestion
    // ast::Pat doesn't have attrs so use &[]
```

Comment (rchaser53) [reply src/patterns.rs]: Oh! I forgot to type it. Thank you.

**Comment by topecongiro** [comment]
Thank you!
