### PR TITLE
don't fail on recoverable parser errors in ignored files

### LINKED ISSUE #3779: gracefully handle recoverable parser errors in ignored files
Refs https://github.com/rust-lang/rustfmt/pull/3777#issuecomment-528326806

### PR DESCRIPTION
**Pull request by calebcartwright**
Resolves #3779 and refs #3777 

This updates how rustfmt handles parser errors when the parser was able to recover from all the errors, and all those errors came from ignored files:
1. Don't emit recovered parser error text for ignored files
2. Don't fail rustfmt when the only parse errors originated in ignored files and were recovered by the parser

This was implemented via a custom Emitter that checks each of the parser errors as they roll through, and keeps track of whether all of the parser errors originated from ignored files. If the parser encountered errors, but was able to recover from them all, then that indicator is checked to determine if the error count can be reset.

AFAICT it is necessary to track that status within the emitter as neither the [Parser](https://doc.rust-lang.org/nightly/nightly-rustc/syntax/parse/parser/struct.Parser.html), [ParseSess](https://doc.rust-lang.org/nightly/nightly-rustc/syntax/parse/struct.ParseSess.html), nor [Handler](https://docs.rs/rustc-ap-rustc_errors/583.0.0/rustc_errors/struct.DiagnosticBuilder.html#structfield.handler) publically expose details about the parser errors encountered; only a true/false flag indicating whether _any_ errors were encountered.

I also investigated whether we could cancel/remove parser errors that met the ignore file condition from _within_ the emitter, but this was not viable either as a mutable reference is required to be able to cancel the DiagnosticBuilder, reseting the DB's Handler error count from the emitter does not remove the error from the parser (see below https://github.com/rust-lang/rustfmt/pull/3782#discussion_r330636355 for why this is the case), etc.

### CODE REVIEW

File: src/formatting.rs [hunk 1]
```diff
@@ -27,6 +28,8 @@ mod newline_style;
 pub(crate) type SourceFile = Vec<FileRecord>;
 pub(crate) type FileRecord = (FileName, String);
 
+thread_local!(static CAN_RESET_CRATE_PARSE_ERRORS: Cell<bool> = Cell::new(false));
```
Comment (calebcartwright) [inline src/formatting.rs]: As mentioned in the PR description, I'm not crazy about using a global here 😞 I got the idea when I saw something similar being leveraged internally in the parser:

- https://github.com/rust-lang/rust/blob/52b3d1f2eb339a2c414b7a18bdf5331308a69192/src/librustc_errors/lib.rs#L333
- https://github.com/rust-lang/rust/blob/52b3d1f2eb339a2c414b7a18bdf5331308a69192/src/librustc_errors/lib.rs#L668-L679

I briefly considered trying to hook into that `TRACKING_DIAGNOSTICS`, though it seems that to do so I'd still need a global to store the Diagnostic events as they roll through, and would then have to re-analyze them all after parsing, so went this route instead.

File: src/formatting.rs [hunk 2]
```diff
@@ -705,7 +770,24 @@ fn make_parse_sess(source_map: Rc<SourceMap>, config: &Config) -> ParseSess {
         } else {
             ColorConfig::Never
         };
-        Handler::with_tty_emitter(color_cfg, true, None, Some(source_map.clone()))
+
+        let emitter_writer =
+            EmitterWriter::stderr(color_cfg, Some(source_map.clone()), false, false, None);
```
Comment (calebcartwright) [inline src/formatting.rs]: this is the emitter that `Handler::with_tty_emitter` creates internally, so creating it here and including it in the custom `Emitter` info so that parser errors that occur in non-ignored files are still displayed as usual

File: src/formatting.rs [hunk 3]
```diff
@@ -683,6 +701,45 @@ fn parse_crate(
     Err(ErrorKind::ParseError)
 }
 
+struct SilentOnIgnoredFilesEmitter {
+    ignore_path_set: IgnorePathSet,
+    source_map: Rc<SourceMap>,
+    emitter: EmitterWriter,
+    can_reset: bool,
+    has_non_ignorable_parser_errors: bool,
+    parser_error_resetter: Rc<RefCell<bool>>,
```
Comment (calebcartwright) [inline src/formatting.rs]: Seems that [Handler](https://docs.rs/rustc-ap-rustc_errors/583.0.0/rustc_errors/struct.Handler.html) requires a [Boxed Emitter with a static lifetime](https://docs.rs/rustc-ap-rustc_errors/583.0.0/rustc_errors/struct.Handler.html#method.with_emitter_and_flags) and I could not see a way around the conflicting lifetime requirements to be able to use a mutable reference:
https://github.com/rust-lang/rust/blob/52b3d1f2eb339a2c414b7a18bdf5331308a69192/src/librustc_errors/lib.rs#L305

Comment (topecongiro) [reply src/formatting.rs]: Ideally we can somehow and and use a getter method on `SilentOnIgnoredFilesEmitter` instead of the mutable reference. Unfortunately doing so seems quite hard given that `Handler` will erase the type to `Emitter` 🤷‍♂

File: src/formatting.rs [hunk 4]
```diff
@@ -705,7 +767,25 @@ fn make_parse_sess(source_map: Rc<SourceMap>, config: &Config) -> ParseSess {
...
+            EmitterWriter::stderr(color_cfg, Some(source_map.clone()), false, false, None);
+        let emitter = Box::new(SilentOnIgnoredFilesEmitter {
+            has_non_ignorable_parser_errors: false,
+            can_reset: false,
+            ignore_path_set: ignore_path_set,
+            source_map: source_map.clone(),
+            emitter: emitter_writer,
+            parser_error_resetter,
+        });
+        Handler::with_emitter_and_flags(
```
Comment (topecongiro) [inline src/formatting.rs]: Nit: could we use `Handler::with_emitter` here as well?

Comment (calebcartwright) [reply src/formatting.rs]: Yeah I think we probably can. I think I used `with_emitter_and_flags` at one point to see if there were any helpful flags I could use and forgot to change it back 😄

File: src/formatting.rs [hunk 5]
```diff
@@ -683,6 +701,45 @@ fn parse_crate(
     Err(ErrorKind::ParseError)
 }
 
+struct SilentOnIgnoredFilesEmitter {
+    ignore_path_set: Rc<IgnorePathSet>,
+    source_map: Rc<SourceMap>,
+    emitter: EmitterWriter,
+    can_reset: bool,
```
[the remark this answers is not in the document]
Comment (calebcartwright) [reply src/formatting.rs]: Sure! I was trying to avoid having to do a `borrow_mut` and update the value unless absolutely necessary, and that was accomplished via both `can_reset` and `has_non_ignorable_parser_errors`. If there was only `has_non_ignorable_parser_errors`, then there could be a lot of repetitive `borrow_mut` setting the value to `true` over and over. 

I'm not sure if/how problematic that would be, but that was my thought process anyway. I could add some inline comments to explain that, or I could remove it altogether if you'd prefer

File: src/formatting.rs (hunk 3 above)
Comment (calebcartwright) [reply src/formatting.rs]: Agreed! The other problem is that the Handler doesn't publicly expose access to its emitter either

File: src/formatting.rs (hunk 5 above)
[the remark this answers is not in the document]
Comment (topecongiro) [reply src/formatting.rs]: Ah, so is `can_reset` used to avoid the overhead of calling `borrow_mut` multiple times? If that is the case, IMHO, this seems premature optimization to me. `RefMut::borrow_mut` is quite cheap (some non-atomic counter operations), and the code path is not hot anyway (it's only run on parse error).

[the remark this answers is not in the document]
Comment (topecongiro) [reply src/formatting.rs]: Is it possible to remove `can_reset` and `has_non_ignorable_parser_errors` without changing the semantic? If possible, then I prefer to remove them to keep the code simple.

[the remark this answers is not in the document]
Comment (calebcartwright) [reply src/formatting.rs]: > Ah, so is can_reset used to avoid the overhead of calling borrow_mut multiple times?

Basically yes, and also because I wasn't sure if there'd ever be any competing borrow attempts which I'd [read](https://doc.rust-lang.org/beta/std/cell/struct.RefCell.html#method.borrow_mut) would panic. Sounds like there's no issues there so I'll remove that 👍 

> Is it possible to remove can_reset and has_non_ignorable_parser_errors without changing the semantic?

I can remove one of them, but AFAICT we'll need at least one flag to indicate whether parser errors from _non-ignored_ files were encountered to ensure that we still fail in such a scenario. For example, if there are two files that have parser errors, `foo.rs` and `bar.rs`, and `bar.rs` is ignored, and `foo` is processed first and then `bar`. We should still fail due to the parser error in `foo.rs`

[the remark this answers is not in the document]
Comment (calebcartwright) [reply src/formatting.rs]: I've updated this to only use the one flag. The only way I could see to remove them both would be to set the top level reset value to `true`, and then updating the emitter logic. 
https://github.com/rust-lang/rustfmt/blob/0531683677eb82dc9f586e9ad51ad1a35bd18e29/src/formatting.rs#L79

However, I don't think that the default behavior should be to ignore/reset parse errors encountered while parsing the crate. I fear that could result in spurious ignores of parser errors which would later cause problems when trying to parse the modules.

IMO it's better to have the emitter keep track of whether it saw a parser error from a non-ignored file via a flag, but please let me know if you'd prefer I change to the other approach!

File: src/formatting.rs [hunk 6]
```diff
@@ -683,6 +701,40 @@ fn parse_crate(
...
+        if let Some(primary_span) = &db.span.primary_span() {
+            let file_name = self.source_map.span_to_filename(*primary_span);
+            match file_name {
+                syntax_pos::FileName::Real(ref path) => {
+                    if self
+                        .ignore_path_set
+                        .is_match(&FileName::Real(path.to_path_buf()))
+                    {
+                        if !self.has_non_ignorable_parser_errors {
+                            *self.can_reset.borrow_mut() = true;
```
Comment (topecongiro) [inline src/formatting.rs]: I first thought that we could simply call `db.handler.reset_err_count();` here instead, but looks like the rustc parser bumps the error count **after** calling `emit_diagnostic`:

https://github.com/rust-lang/rust/blob/f2023ac599c38a59f86552089e6791c5a73412d3/src/librustc_errors/lib.rs#L781-L791

Also like you mentioned, resetting the error count may cause skipping important parsing errors.

Comment (calebcartwright) [reply src/formatting.rs]: > I first thought that we could simply call db.handler.reset_err_count();

That's what I was expecting originally too 👍 

> here instead, but looks like the rustc parser bumps the error count after calling emit_diagnostic:

Thank you so much for finding that! I was baffled how calling `reset_err_count()` inside `emit_diagnostic` seemed to be doing nothing, but that makes much more sense now

**Comment by topecongiro** [comment]
@calebcartwright Working on #3835, I found that there were some refactorings around `rustc_errors` and breaking changes to its API. As #3835 is required to fix the broken build on the latest nightly, I am going to merge it first, but that would likely cause conflicts with this PR. Sorry for the inconvenience.

**Comment by calebcartwright** [comment]
@topecongiro - no worries! I'll update this to address any merge conflicts afterwards

**Comment by calebcartwright** [comment]
Fortunately looks like the merge conflicts are fairly minimal. I need to grab `nightly-2019-10-04-x86_64-unknown-linux-gnu` to make sure this is still working as expected since there were changes in `rustc_errors`. Will push the merge resolution after 👍

**Comment by topecongiro** [comment]
Perfect, thank you for all the work :tada:
